//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.14 at 02:56:20 PM PST 
//


package com.mitchell.estimate.resource.dto.parts;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for InventoryStatusEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="InventoryStatusEnum">
 *   &lt;restriction base="{http://www.cieca.com/BMS}ClosedEnum">
 *     &lt;enumeration value="Available"/>
 *     &lt;enumeration value="BackOrdered"/>
 *     &lt;enumeration value="Discontinued"/>
 *     &lt;enumeration value="NotAvailable"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "InventoryStatusEnum")
@XmlEnum
public enum InventoryStatusEnum {

    @XmlEnumValue("Available")
    AVAILABLE("Available"),
    @XmlEnumValue("BackOrdered")
    BACK_ORDERED("BackOrdered"),
    @XmlEnumValue("Discontinued")
    DISCONTINUED("Discontinued"),
    @XmlEnumValue("NotAvailable")
    NOT_AVAILABLE("NotAvailable");
    private final String value;

    InventoryStatusEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static InventoryStatusEnum fromValue(String v) {
        for (InventoryStatusEnum c: InventoryStatusEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
