//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.03 at 12:33:26 PM PST 
//


package com.mitchell.estimate.resource.dto.claim;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import com.mitchell.estimate.resource.dto.idinfo.IDInfoType;
import com.mitchell.estimate.resource.dto.loss.LossInfoType;
import com.mitchell.estimate.resource.dto.party.CustomElementType;
import com.mitchell.estimate.resource.dto.party.PartyTypeClosedEnumType;
import com.mitchell.estimate.resource.dto.policy.PolicyInfoType;

/**
 * <p>Java class for ClaimInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ClaimInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ClaimNum" type="{http://www.cieca.com/BMS}MitchellClaimNumType"/>
 *         &lt;element name="ClaimSensitivityInd" type="{http://www.cieca.com/BMS}Indicator" minOccurs="0"/>
 *         &lt;element name="ClaimStatus" type="{http://www.cieca.com/BMS}ClaimStatusClosedEnumType" minOccurs="0"/>
 *         &lt;element name="PolicyInfo" type="{http://www.cieca.com/BMS}PolicyInfoType" minOccurs="0"/>
 *         &lt;element name="LossInfo" type="{http://www.cieca.com/BMS}LossInfoType" minOccurs="0"/>
 *         &lt;element name="AdditionalIDInfo" type="{http://www.cieca.com/BMS}IDInfoType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="ClaimMemo" type="{http://www.cieca.com/BMS}C" minOccurs="0"/>
 *         &lt;element name="PartyType" type="{http://www.cieca.com/BMS}PartyTypeClosedEnumType" minOccurs="0"/>
 *         &lt;element name="CustomElement" type="{http://www.cieca.com/BMS}CustomElementType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ClaimInfoType", propOrder = {
    "claimNum",
    "claimSensitivityInd",
    "claimStatus",
    "policyInfo",
    "lossInfo",
    "additionalIDInfo",
    "claimMemo",
    "partyType",
    "customElement"
})
public class ClaimInfoType implements Serializable
{

    private final static long serialVersionUID = 20120730L;
    @XmlElement(name = "ClaimNum", required = true)
    protected String claimNum;
    @XmlElement(name = "ClaimSensitivityInd")
    protected String claimSensitivityInd;
    @XmlElement(name = "ClaimStatus")
    protected ClaimStatusClosedEnumType claimStatus;
    @XmlElement(name = "PolicyInfo")
    protected PolicyInfoType policyInfo;
    @XmlElement(name = "LossInfo")
    protected LossInfoType lossInfo;
    @XmlElement(name = "AdditionalIDInfo")
    protected List<IDInfoType> additionalIDInfo;
    @XmlElement(name = "ClaimMemo")
    protected String claimMemo;
    @XmlElement(name = "PartyType")
    protected PartyTypeClosedEnumType partyType;
    @XmlElement(name = "CustomElement")
    protected List<CustomElementType> customElement;

    /**
     * Gets the value of the claimNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClaimNum() {
        return claimNum;
    }

    /**
     * Sets the value of the claimNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClaimNum(String value) {
        this.claimNum = value;
    }

    /**
     * Gets the value of the claimSensitivityInd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClaimSensitivityInd() {
        return claimSensitivityInd;
    }

    /**
     * Sets the value of the claimSensitivityInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClaimSensitivityInd(String value) {
        this.claimSensitivityInd = value;
    }

    /**
     * Gets the value of the claimStatus property.
     * 
     * @return
     *     possible object is
     *     {@link ClaimStatusClosedEnumType }
     *     
     */
    public ClaimStatusClosedEnumType getClaimStatus() {
        return claimStatus;
    }

    /**
     * Sets the value of the claimStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link ClaimStatusClosedEnumType }
     *     
     */
    public void setClaimStatus(ClaimStatusClosedEnumType value) {
        this.claimStatus = value;
    }

    /**
     * Gets the value of the policyInfo property.
     * 
     * @return
     *     possible object is
     *     {@link PolicyInfoType }
     *     
     */
    public PolicyInfoType getPolicyInfo() {
        return policyInfo;
    }

    /**
     * Sets the value of the policyInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link PolicyInfoType }
     *     
     */
    public void setPolicyInfo(PolicyInfoType value) {
        this.policyInfo = value;
    }

    /**
     * Gets the value of the lossInfo property.
     * 
     * @return
     *     possible object is
     *     {@link LossInfoType }
     *     
     */
    public LossInfoType getLossInfo() {
        return lossInfo;
    }

    /**
     * Sets the value of the lossInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link LossInfoType }
     *     
     */
    public void setLossInfo(LossInfoType value) {
        this.lossInfo = value;
    }

    /**
     * Gets the value of the additionalIDInfo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the additionalIDInfo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAdditionalIDInfo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IDInfoType }
     * 
     * 
     */
    public List<IDInfoType> getAdditionalIDInfo() {
        if (additionalIDInfo == null) {
            additionalIDInfo = new ArrayList<IDInfoType>();
        }
        return this.additionalIDInfo;
    }

    /**
     * Gets the value of the claimMemo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClaimMemo() {
        return claimMemo;
    }

    /**
     * Sets the value of the claimMemo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClaimMemo(String value) {
        this.claimMemo = value;
    }

    /**
     * Gets the value of the partyType property.
     * 
     * @return
     *     possible object is
     *     {@link PartyTypeClosedEnumType }
     *     
     */
    public PartyTypeClosedEnumType getPartyType() {
        return partyType;
    }

    /**
     * Sets the value of the partyType property.
     * 
     * @param value
     *     allowed object is
     *     {@link PartyTypeClosedEnumType }
     *     
     */
    public void setPartyType(PartyTypeClosedEnumType value) {
        this.partyType = value;
    }

    /**
     * Gets the value of the customElement property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the customElement property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCustomElement().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CustomElementType }
     * 
     * 
     */
    public List<CustomElementType> getCustomElement() {
        if (customElement == null) {
            customElement = new ArrayList<CustomElementType>();
        }
        return this.customElement;
    }

}
