//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.03 at 12:33:26 PM PST 
//


package com.mitchell.estimate.resource.dto.vehicle.condition;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TowConditionClosedEnumType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TowConditionClosedEnumType">
 *   &lt;restriction base="{http://www.cieca.com/BMS}ClosedEnum">
 *     &lt;enumeration value="Drivable"/>
 *     &lt;enumeration value="Not Towable"/>
 *     &lt;enumeration value="Towable"/>
 *     &lt;enumeration value="Unknown"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "TowConditionClosedEnumType")
@XmlEnum
public enum TowConditionClosedEnumType {

    @XmlEnumValue("Drivable")
    DRIVABLE("Drivable"),
    @XmlEnumValue("Not Towable")
    NOT_TOWABLE("Not Towable"),
    @XmlEnumValue("Towable")
    TOWABLE("Towable"),
    @XmlEnumValue("Unknown")
    UNKNOWN("Unknown");
    private final String value;

    TowConditionClosedEnumType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TowConditionClosedEnumType fromValue(String v) {
        for (TowConditionClosedEnumType c: TowConditionClosedEnumType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
