//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.03 at 12:33:26 PM PST 
//


package com.mitchell.estimate.resource.dto.document;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DocumentVersionClosedEnumType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="DocumentVersionClosedEnumType">
 *   &lt;restriction base="{http://www.cieca.com/BMS}ClosedEnum">
 *     &lt;enumeration value="AN"/>
 *     &lt;enumeration value="DE"/>
 *     &lt;enumeration value="OF"/>
 *     &lt;enumeration value="QS"/>
 *     &lt;enumeration value="CO"/>
 *     &lt;enumeration value="DM"/>
 *     &lt;enumeration value="EM"/>
 *     &lt;enumeration value="ME"/>
 *     &lt;enumeration value="RD"/>
 *     &lt;enumeration value="SV"/>
 *     &lt;enumeration value="UD"/>
 *     &lt;enumeration value="UP"/>
 *     &lt;enumeration value="VN"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "DocumentVersionClosedEnumType")
@XmlEnum
public enum DocumentVersionClosedEnumType {

    AN,
    DE,
    OF,
    QS,
    CO,
    DM,
    EM,
    ME,
    RD,
    SV,
    UD,
    UP,
    VN;

    public String value() {
        return name();
    }

    public static DocumentVersionClosedEnumType fromValue(String v) {
        return valueOf(v);
    }

}
