//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.03 at 12:33:26 PM PST 
//


package com.mitchell.estimate.resource.dto.address;

import java.io.Serializable;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for AddressType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AddressType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Address1" type="{http://www.cieca.com/BMS}Char_80" minOccurs="0"/>
 *         &lt;element name="Address2" type="{http://www.cieca.com/BMS}Char_80" minOccurs="0"/>
 *         &lt;element name="SubSiteAddress" type="{http://www.cieca.com/BMS}SubSiteAddressType" minOccurs="0"/>
 *         &lt;element name="City" type="{http://www.cieca.com/BMS}Char_50" minOccurs="0"/>
 *         &lt;element name="StateProvince" type="{http://www.cieca.com/BMS}StateProvinceClosedEnumType" minOccurs="0"/>
 *         &lt;element name="PostalCode" type="{http://www.cieca.com/BMS}Char_15" minOccurs="0"/>
 *         &lt;element name="CountryCode" type="{http://www.cieca.com/BMS}CountryCodeClosedEnumType" minOccurs="0"/>
 *         &lt;element name="LocationDesc" type="{http://www.cieca.com/BMS}Char_80" minOccurs="0"/>
 *         &lt;element name="LocationType" type="{http://www.cieca.com/BMS}LocationTypeOpenEnumType" minOccurs="0"/>
 *         &lt;element name="CoordinateInfo" type="{http://www.cieca.com/BMS}CoordinateInfoType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AddressType", propOrder = {
    "address1",
    "address2",
    "subSiteAddress",
    "city",
    "stateProvince",
    "postalCode",
    "countryCode",
    "locationDesc",
    "locationType",
    "coordinateInfo"
})
public class AddressType
    implements Serializable
{

    private final static long serialVersionUID = 20120730L;
    @XmlElement(name = "Address1")
    protected String address1;
    @XmlElement(name = "Address2")
    protected String address2;
    @XmlElement(name = "SubSiteAddress")
    protected SubSiteAddressType subSiteAddress;
    @XmlElement(name = "City")
    protected String city;
    @XmlElement(name = "StateProvince")
    protected StateProvinceClosedEnumType stateProvince;
    @XmlElement(name = "PostalCode")
    protected String postalCode;
    @XmlElement(name = "CountryCode")
    protected CountryCodeClosedEnumType countryCode;
    @XmlElement(name = "LocationDesc")
    protected String locationDesc;
    @XmlElement(name = "LocationType")
    protected LocationTypeOpenEnumType locationType;
    @XmlElement(name = "CoordinateInfo")
    protected CoordinateInfoType coordinateInfo;

    /**
     * Gets the value of the address1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddress1() {
        return address1;
    }

    /**
     * Sets the value of the address1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddress1(String value) {
        this.address1 = value;
    }

    /**
     * Gets the value of the address2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddress2() {
        return address2;
    }

    /**
     * Sets the value of the address2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddress2(String value) {
        this.address2 = value;
    }

    /**
     * Gets the value of the subSiteAddress property.
     * 
     * @return
     *     possible object is
     *     {@link SubSiteAddressType }
     *     
     */
    public SubSiteAddressType getSubSiteAddress() {
        return subSiteAddress;
    }

    /**
     * Sets the value of the subSiteAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubSiteAddressType }
     *     
     */
    public void setSubSiteAddress(SubSiteAddressType value) {
        this.subSiteAddress = value;
    }

    /**
     * Gets the value of the city property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCity() {
        return city;
    }

    /**
     * Sets the value of the city property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCity(String value) {
        this.city = value;
    }

    /**
     * Gets the value of the stateProvince property.
     * 
     * @return
     *     possible object is
     *     {@link StateProvinceClosedEnumType }
     *     
     */
    public StateProvinceClosedEnumType getStateProvince() {
        return stateProvince;
    }

    /**
     * Sets the value of the stateProvince property.
     * 
     * @param value
     *     allowed object is
     *     {@link StateProvinceClosedEnumType }
     *     
     */
    public void setStateProvince(StateProvinceClosedEnumType value) {
        this.stateProvince = value;
    }

    /**
     * Gets the value of the postalCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPostalCode() {
        return postalCode;
    }

    /**
     * Sets the value of the postalCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPostalCode(String value) {
        this.postalCode = value;
    }

    /**
     * Gets the value of the countryCode property.
     * 
     * @return
     *     possible object is
     *     {@link CountryCodeClosedEnumType }
     *     
     */
    public CountryCodeClosedEnumType getCountryCode() {
        return countryCode;
    }

    /**
     * Sets the value of the countryCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link CountryCodeClosedEnumType }
     *     
     */
    public void setCountryCode(CountryCodeClosedEnumType value) {
        this.countryCode = value;
    }

    /**
     * Gets the value of the locationDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocationDesc() {
        return locationDesc;
    }

    /**
     * Sets the value of the locationDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocationDesc(String value) {
        this.locationDesc = value;
    }

    /**
     * Gets the value of the locationType property.
     * 
     * @return
     *     possible object is
     *     {@link LocationTypeOpenEnumType }
     *     
     */
    public LocationTypeOpenEnumType getLocationType() {
        return locationType;
    }

    /**
     * Sets the value of the locationType property.
     * 
     * @param value
     *     allowed object is
     *     {@link LocationTypeOpenEnumType }
     *     
     */
    public void setLocationType(LocationTypeOpenEnumType value) {
        this.locationType = value;
    }

    /**
     * Gets the value of the coordinateInfo property.
     * 
     * @return
     *     possible object is
     *     {@link CoordinateInfoType }
     *     
     */
    public CoordinateInfoType getCoordinateInfo() {
        return coordinateInfo;
    }

    /**
     * Sets the value of the coordinateInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link CoordinateInfoType }
     *     
     */
    public void setCoordinateInfo(CoordinateInfoType value) {
        this.coordinateInfo = value;
    }

}
