//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.03 at 12:33:26 PM PST 
//


package com.mitchell.estimate.resource.service.dto.inspection;

import java.io.Serializable;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for InspectionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="InspectionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="InspectionCode" type="{http://www.cieca.com/BMS}InspectionCodeClosedEnumType" minOccurs="0"/>
 *         &lt;element name="InspectionSiteCode" type="{http://www.cieca.com/BMS}InspectionDescriptionClosedEnumType" minOccurs="0"/>
 *         &lt;element name="InspectionDesc" type="{http://www.cieca.com/BMS}InspectionDescriptionOpenEnumType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InspectionType", propOrder = {
    "inspectionCode",
    "inspectionSiteCode",
    "inspectionDesc"
})
public class InspectionType
    implements Serializable
{

    private final static long serialVersionUID = 20120730L;
    @XmlElement(name = "InspectionCode")
    protected InspectionCodeClosedEnumType inspectionCode;
    @XmlElement(name = "InspectionSiteCode")
    protected InspectionDescriptionClosedEnumType inspectionSiteCode;
    @XmlElement(name = "InspectionDesc")
    protected InspectionDescriptionOpenEnumType inspectionDesc;

    /**
     * Gets the value of the inspectionCode property.
     * 
     * @return
     *     possible object is
     *     {@link InspectionCodeClosedEnumType }
     *     
     */
    public InspectionCodeClosedEnumType getInspectionCode() {
        return inspectionCode;
    }

    /**
     * Sets the value of the inspectionCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link InspectionCodeClosedEnumType }
     *     
     */
    public void setInspectionCode(InspectionCodeClosedEnumType value) {
        this.inspectionCode = value;
    }

    /**
     * Gets the value of the inspectionSiteCode property.
     * 
     * @return
     *     possible object is
     *     {@link InspectionDescriptionClosedEnumType }
     *     
     */
    public InspectionDescriptionClosedEnumType getInspectionSiteCode() {
        return inspectionSiteCode;
    }

    /**
     * Sets the value of the inspectionSiteCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link InspectionDescriptionClosedEnumType }
     *     
     */
    public void setInspectionSiteCode(InspectionDescriptionClosedEnumType value) {
        this.inspectionSiteCode = value;
    }

    /**
     * Gets the value of the inspectionDesc property.
     * 
     * @return
     *     possible object is
     *     {@link InspectionDescriptionOpenEnumType }
     *     
     */
    public InspectionDescriptionOpenEnumType getInspectionDesc() {
        return inspectionDesc;
    }

    /**
     * Sets the value of the inspectionDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link InspectionDescriptionOpenEnumType }
     *     
     */
    public void setInspectionDesc(InspectionDescriptionOpenEnumType value) {
        this.inspectionDesc = value;
    }

}
