//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.03 at 12:33:26 PM PST 
//


package com.mitchell.estimate.resource.vehicle.color;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ColorCodesClosedEnumType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ColorCodesClosedEnumType">
 *   &lt;restriction base="{http://www.cieca.com/BMS}ClosedEnum">
 *     &lt;enumeration value="AME"/>
 *     &lt;enumeration value="BGE"/>
 *     &lt;enumeration value="BLK"/>
 *     &lt;enumeration value="BLU"/>
 *     &lt;enumeration value="BRD"/>
 *     &lt;enumeration value="BRO"/>
 *     &lt;enumeration value="BRZ"/>
 *     &lt;enumeration value="CAM"/>
 *     &lt;enumeration value="COM"/>
 *     &lt;enumeration value="CPR"/>
 *     &lt;enumeration value="CRM"/>
 *     &lt;enumeration value="DBL"/>
 *     &lt;enumeration value="DGR"/>
 *     &lt;enumeration value="GLD"/>
 *     &lt;enumeration value="GRN"/>
 *     &lt;enumeration value="GRY"/>
 *     &lt;enumeration value="LAV"/>
 *     &lt;enumeration value="LBL"/>
 *     &lt;enumeration value="LGR"/>
 *     &lt;enumeration value="MAR"/>
 *     &lt;enumeration value="MVE"/>
 *     &lt;enumeration value="ORG"/>
 *     &lt;enumeration value="OTR"/>
 *     &lt;enumeration value="PKN"/>
 *     &lt;enumeration value="PLE"/>
 *     &lt;enumeration value="RED"/>
 *     &lt;enumeration value="SIL"/>
 *     &lt;enumeration value="TAN"/>
 *     &lt;enumeration value="TEA"/>
 *     &lt;enumeration value="TPE"/>
 *     &lt;enumeration value="TRQ"/>
 *     &lt;enumeration value="UNK"/>
 *     &lt;enumeration value="WHI"/>
 *     &lt;enumeration value="YEL"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ColorCodesClosedEnumType")
@XmlEnum
public enum ColorCodesClosedEnumType {

    AME,
    BGE,
    BLK,
    BLU,
    BRD,
    BRO,
    BRZ,
    CAM,
    COM,
    CPR,
    CRM,
    DBL,
    DGR,
    GLD,
    GRN,
    GRY,
    LAV,
    LBL,
    LGR,
    MAR,
    MVE,
    ORG,
    OTR,
    PKN,
    PLE,
    RED,
    SIL,
    TAN,
    TEA,
    TPE,
    TRQ,
    UNK,
    WHI,
    YEL;

    public String value() {
        return name();
    }

    public static ColorCodesClosedEnumType fromValue(String v) {
        return valueOf(v);
    }

}
