//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.03 at 12:33:26 PM PST 
//


package com.mitchell.estimate.resource.entity.profile;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import com.mitchell.estimate.resource.entity.rate.BettermentRateInfoType;
import com.mitchell.estimate.resource.entity.rate.LaborRateInfoType;
import com.mitchell.estimate.resource.entity.rate.MaterialsRateInfoType;
import com.mitchell.estimate.resource.entity.rate.OtherRateInfoType;
import com.mitchell.estimate.resource.entity.rate.PartsRateInfoType;
import com.mitchell.estimate.resource.entity.rate.RateInfoType;
import com.mitchell.estimate.resource.entity.rate.tax.CanadianTaxType;

/**
 * <p>Java class for ProfileInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ProfileInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ProfileName" type="{http://www.cieca.com/BMS}Char_40" minOccurs="0"/>
 *         &lt;element name="RateInfo" type="{http://www.cieca.com/BMS}RateInfoType" maxOccurs="unbounded"/>
 *         &lt;element name="CostPlusBasisInd" type="{http://www.cieca.com/BMS}Boolean" minOccurs="0"/>
 *         &lt;element name="DrillTimeInd" type="{http://www.cieca.com/BMS}Boolean" minOccurs="0"/>
 *         &lt;element name="EdgingTimeInd" type="{http://www.cieca.com/BMS}Boolean" minOccurs="0"/>
 *         &lt;element name="UndersideTimeInd" type="{http://www.cieca.com/BMS}Boolean" minOccurs="0"/>
 *         &lt;element name="VIRCompletedInd" type="{http://www.cieca.com/BMS}Boolean" minOccurs="0"/>
 *         &lt;element name="BettermentInd" type="{http://www.cieca.com/BMS}Boolean" minOccurs="0"/>
 *         &lt;element name="CanadianTax" type="{http://www.cieca.com/BMS}CanadianTaxType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ProfileInfoType", propOrder = {
    "profileName",
    "rateInfo",
    "laborRateInfo",
    "partsRateInfo",
    "materialsRateInfo",
    "bettermentRateInfo",
    "otherRateInfo",
    "costPlusBasisInd",
    "drillTimeInd",
    "edgingTimeInd",
    "undersideTimeInd",
    "virCompletedInd",
    "bettermentInd",
    "canadianTax"
})
public class ProfileInfoType
    implements Serializable
{

    private final static long serialVersionUID = 20120730L;
    
    @XmlElement(name = "ProfileName")
    protected String profileName;
    
    @XmlElement(name = "RateInfo", required = true)
    protected List<RateInfoType> rateInfo;

    @XmlElement(name = "LaborRateInfo", required = true)
    protected List<LaborRateInfoType> laborRateInfo;
    
    @XmlElement(name = "PartsRateInfo", required = true)
    protected List<PartsRateInfoType> partsRateInfo;
    
    @XmlElement(name = "MaterialsRateInfo", required = true)
    protected List<MaterialsRateInfoType> materialsRateInfo;
    
    @XmlElement(name = "BettermentRateInfo", required = true)
    protected List<BettermentRateInfoType> bettermentRateInfo;
    
    @XmlElement(name = "OtherRateInfo", required = true)
    protected List<OtherRateInfoType> otherRateInfo;
    
    @XmlElement(name = "CostPlusBasisInd")
    protected Boolean costPlusBasisInd;
    
    @XmlElement(name = "DrillTimeInd")
    protected Boolean drillTimeInd;
    
    @XmlElement(name = "EdgingTimeInd")
    protected Boolean edgingTimeInd;
    
    @XmlElement(name = "UndersideTimeInd")
    protected Boolean undersideTimeInd;
    
    @XmlElement(name = "VIRCompletedInd")
    protected Boolean virCompletedInd;
    
    @XmlElement(name = "BettermentInd")
    protected Boolean bettermentInd;
    
    @XmlElement(name = "CanadianTax")
    protected CanadianTaxType canadianTax;

    /**
     * Gets the value of the profileName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProfileName() {
        return profileName;
    }

    /**
     * Sets the value of the profileName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProfileName(String value) {
        this.profileName = value;
    }

    /**
     * Gets the value of the rateInfo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the rateInfo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRateInfo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RateInfoType }
     * 
     * 
     */
    public List<RateInfoType> getRateInfo() {
        if (rateInfo == null) {
            rateInfo = new ArrayList<RateInfoType>();
        }
        return this.rateInfo;
    }

    /**
     * Gets the value of the laborRateInfo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the laborRateInfo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLaborRateInfo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LaborRateInfoType }
     * 
     * 
     */
    public List<LaborRateInfoType> getLaborRateInfo() {
        if (laborRateInfo == null) {
            laborRateInfo = new ArrayList<LaborRateInfoType>();
        }
        return this.laborRateInfo;
    }

    /**
     * Gets the value of the partsRateInfo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the partsRateInfo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPartsRateInfo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PartsRateInfoType }
     * 
     * 
     */
    public List<PartsRateInfoType> getPartsRateInfo() {
        if (partsRateInfo == null) {
            partsRateInfo = new ArrayList<PartsRateInfoType>();
        }
        return this.partsRateInfo;
    }

    /**
     * Gets the value of the materialsRateInfo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the materialsRateInfo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMaterialsRateInfo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MaterialsRateInfoType }
     * 
     * 
     */
    public List<MaterialsRateInfoType> getMaterialsRateInfo() {
        if (materialsRateInfo == null) {
            materialsRateInfo = new ArrayList<MaterialsRateInfoType>();
        }
        return this.materialsRateInfo;
    }

    /**
     * Gets the value of the bettermentRateInfo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the bettermentRateInfo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBettermentRateInfo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BettermentRateInfoType }
     * 
     * 
     */
    public List<BettermentRateInfoType> getBettermentRateInfo() {
        if (bettermentRateInfo == null) {
            bettermentRateInfo = new ArrayList<BettermentRateInfoType>();
        }
        return this.bettermentRateInfo;
    }

    /**
     * Gets the value of the otherRateInfo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the otherRateInfo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOtherRateInfo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OtherRateInfoType }
     * 
     * 
     */
    public List<OtherRateInfoType> getOtherRateInfo() {
        if (otherRateInfo == null) {
            otherRateInfo = new ArrayList<OtherRateInfoType>();
        }
        return this.otherRateInfo;
    }

    /**
     * Gets the value of the costPlusBasisInd property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isCostPlusBasisInd() {
        return costPlusBasisInd;
    }

    /**
     * Sets the value of the costPlusBasisInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCostPlusBasisInd(Boolean value) {
        this.costPlusBasisInd = value;
    }

    /**
     * Gets the value of the drillTimeInd property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDrillTimeInd() {
        return drillTimeInd;
    }

    /**
     * Sets the value of the drillTimeInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDrillTimeInd(Boolean value) {
        this.drillTimeInd = value;
    }

    /**
     * Gets the value of the edgingTimeInd property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isEdgingTimeInd() {
        return edgingTimeInd;
    }

    /**
     * Sets the value of the edgingTimeInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setEdgingTimeInd(Boolean value) {
        this.edgingTimeInd = value;
    }

    /**
     * Gets the value of the undersideTimeInd property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isUndersideTimeInd() {
        return undersideTimeInd;
    }

    /**
     * Sets the value of the undersideTimeInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setUndersideTimeInd(Boolean value) {
        this.undersideTimeInd = value;
    }

    /**
     * Gets the value of the virCompletedInd property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isVIRCompletedInd() {
        return virCompletedInd;
    }

    /**
     * Sets the value of the virCompletedInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setVIRCompletedInd(Boolean value) {
        this.virCompletedInd = value;
    }

    /**
     * Gets the value of the bettermentInd property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isBettermentInd() {
        return bettermentInd;
    }

    /**
     * Sets the value of the bettermentInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setBettermentInd(Boolean value) {
        this.bettermentInd = value;
    }

    /**
     * Gets the value of the canadianTax property.
     * 
     * @return
     *     possible object is
     *     {@link CanadianTaxType }
     *     
     */
    public CanadianTaxType getCanadianTax() {
        return canadianTax;
    }

    /**
     * Sets the value of the canadianTax property.
     * 
     * @param value
     *     allowed object is
     *     {@link CanadianTaxType }
     *     
     */
    public void setCanadianTax(CanadianTaxType value) {
        this.canadianTax = value;
    }

}
