//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.03 at 12:33:26 PM PST 
//


package com.mitchell.estimate.resource.address;

import java.io.Serializable;
import java.math.BigDecimal;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for CoordinateInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CoordinateInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element name="Latitude" type="{http://www.cieca.com/BMS}Decimal_Range_-180.000000-180.000000"/>
 *           &lt;element name="LatitudeDetail" type="{http://www.cieca.com/BMS}LatitudeLongitudeDetailType"/>
 *         &lt;/choice>
 *         &lt;choice>
 *           &lt;element name="Longitude" type="{http://www.cieca.com/BMS}Decimal_Range_-180.000000-180.000000"/>
 *           &lt;element name="LongitudeDetail" type="{http://www.cieca.com/BMS}LatitudeLongitudeDetailType"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CoordinateInfoType", propOrder = {
    "latitude",
    "latitudeDetail",
    "longitude",
    "longitudeDetail"
})
public class CoordinateInfoType implements Serializable
{

    private final static long serialVersionUID = 20120730L;
    @XmlElement(name = "Latitude")
    protected BigDecimal latitude;
    @XmlElement(name = "LatitudeDetail")
    protected LatitudeLongitudeDetailType latitudeDetail;
    @XmlElement(name = "Longitude")
    protected BigDecimal longitude;
    @XmlElement(name = "LongitudeDetail")
    protected LatitudeLongitudeDetailType longitudeDetail;

    /**
     * Gets the value of the latitude property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getLatitude() {
        return latitude;
    }

    /**
     * Sets the value of the latitude property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setLatitude(BigDecimal value) {
        this.latitude = value;
    }

    /**
     * Gets the value of the latitudeDetail property.
     * 
     * @return
     *     possible object is
     *     {@link LatitudeLongitudeDetailType }
     *     
     */
    public LatitudeLongitudeDetailType getLatitudeDetail() {
        return latitudeDetail;
    }

    /**
     * Sets the value of the latitudeDetail property.
     * 
     * @param value
     *     allowed object is
     *     {@link LatitudeLongitudeDetailType }
     *     
     */
    public void setLatitudeDetail(LatitudeLongitudeDetailType value) {
        this.latitudeDetail = value;
    }

    /**
     * Gets the value of the longitude property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getLongitude() {
        return longitude;
    }

    /**
     * Sets the value of the longitude property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setLongitude(BigDecimal value) {
        this.longitude = value;
    }

    /**
     * Gets the value of the longitudeDetail property.
     * 
     * @return
     *     possible object is
     *     {@link LatitudeLongitudeDetailType }
     *     
     */
    public LatitudeLongitudeDetailType getLongitudeDetail() {
        return longitudeDetail;
    }

    /**
     * Sets the value of the longitudeDetail property.
     * 
     * @param value
     *     allowed object is
     *     {@link LatitudeLongitudeDetailType }
     *     
     */
    public void setLongitudeDetail(LatitudeLongitudeDetailType value) {
        this.longitudeDetail = value;
    }

}
