//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.03 at 12:33:26 PM PST 
//


package com.mitchell.estimate.resource.address;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LatitudeLongitudeDetailType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LatitudeLongitudeDetailType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Degrees" type="{http://www.cieca.com/BMS}Integer_Range_0-180"/>
 *         &lt;element name="Minutes" type="{http://www.cieca.com/BMS}Integer_Range_0-59"/>
 *         &lt;element name="Seconds" type="{http://www.cieca.com/BMS}Integer_Range_0-59"/>
 *         &lt;element name="Direction" type="{http://www.cieca.com/BMS}Char_1" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LatitudeLongitudeDetailType", propOrder = {
    "degrees",
    "minutes",
    "seconds",
    "direction"
})
public class LatitudeLongitudeDetailType
    implements Serializable
{

    private final static long serialVersionUID = 20120730L;
    @XmlElement(name = "Degrees")
    protected int degrees;
    @XmlElement(name = "Minutes")
    protected int minutes;
    @XmlElement(name = "Seconds")
    protected int seconds;
    @XmlElement(name = "Direction")
    protected String direction;

    /**
     * Gets the value of the degrees property.
     * 
     */
    public int getDegrees() {
        return degrees;
    }

    /**
     * Sets the value of the degrees property.
     * 
     */
    public void setDegrees(int value) {
        this.degrees = value;
    }

    /**
     * Gets the value of the minutes property.
     * 
     */
    public int getMinutes() {
        return minutes;
    }

    /**
     * Sets the value of the minutes property.
     * 
     */
    public void setMinutes(int value) {
        this.minutes = value;
    }

    /**
     * Gets the value of the seconds property.
     * 
     */
    public int getSeconds() {
        return seconds;
    }

    /**
     * Sets the value of the seconds property.
     * 
     */
    public void setSeconds(int value) {
        this.seconds = value;
    }

    /**
     * Gets the value of the direction property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDirection() {
        return direction;
    }

    /**
     * Sets the value of the direction property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDirection(String value) {
        this.direction = value;
    }

}
