//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.03 at 12:33:26 PM PST 
//


package com.mitchell.estimate.resource.service.dto.party;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CancellationReasonClosedEnumType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="CancellationReasonClosedEnumType">
 *   &lt;restriction base="{http://www.cieca.com/BMS}ClosedEnum">
 *     &lt;enumeration value="Claim Denial"/>
 *     &lt;enumeration value="Donation"/>
 *     &lt;enumeration value="Duplicate"/>
 *     &lt;enumeration value="Government Action"/>
 *     &lt;enumeration value="Other"/>
 *     &lt;enumeration value="Owner Retained"/>
 *     &lt;enumeration value="Police"/>
 *     &lt;enumeration value="Provider Request"/>
 *     &lt;enumeration value="Repaired"/>
 *     &lt;enumeration value="Title Unattainable"/>
 *     &lt;enumeration value="Transferred"/>
 *     &lt;enumeration value="Unknown"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "CancellationReasonClosedEnumType")
@XmlEnum
public enum CancellationReasonClosedEnumType {

    @XmlEnumValue("Claim Denial")
    CLAIM_DENIAL("Claim Denial"),
    @XmlEnumValue("Donation")
    DONATION("Donation"),
    @XmlEnumValue("Duplicate")
    DUPLICATE("Duplicate"),
    @XmlEnumValue("Government Action")
    GOVERNMENT_ACTION("Government Action"),
    @XmlEnumValue("Other")
    OTHER("Other"),
    @XmlEnumValue("Owner Retained")
    OWNER_RETAINED("Owner Retained"),
    @XmlEnumValue("Police")
    POLICE("Police"),
    @XmlEnumValue("Provider Request")
    PROVIDER_REQUEST("Provider Request"),
    @XmlEnumValue("Repaired")
    REPAIRED("Repaired"),
    @XmlEnumValue("Title Unattainable")
    TITLE_UNATTAINABLE("Title Unattainable"),
    @XmlEnumValue("Transferred")
    TRANSFERRED("Transferred"),
    @XmlEnumValue("Unknown")
    UNKNOWN("Unknown");
    private final String value;

    CancellationReasonClosedEnumType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CancellationReasonClosedEnumType fromValue(String v) {
        for (CancellationReasonClosedEnumType c: CancellationReasonClosedEnumType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
