//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.03 at 12:33:26 PM PST 
//


package com.mitchell.estimate.resource.service.dto.party;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PartyTypeClosedEnumType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="PartyTypeClosedEnumType">
 *   &lt;restriction base="{http://www.cieca.com/BMS}ClosedEnum">
 *     &lt;enumeration value="Adjuster"/>
 *     &lt;enumeration value="Administrator of an Estate"/>
 *     &lt;enumeration value="Agent"/>
 *     &lt;enumeration value="Alternate Person to be Surveyed"/>
 *     &lt;enumeration value="Arbitration Services"/>
 *     &lt;enumeration value="Arbitrator"/>
 *     &lt;enumeration value="Attorney"/>
 *     &lt;enumeration value="Bid Contact"/>
 *     &lt;enumeration value="Bid Source"/>
 *     &lt;enumeration value="Claimant"/>
 *     &lt;enumeration value="Coast Guard"/>
 *     &lt;enumeration value="Consolidator"/>
 *     &lt;enumeration value="Consumer Product Safety Commission"/>
 *     &lt;enumeration value="Contract Business"/>
 *     &lt;enumeration value="Corporate"/>
 *     &lt;enumeration value="Corporate Owned"/>
 *     &lt;enumeration value="Court Assigned Representative"/>
 *     &lt;enumeration value="Court Official"/>
 *     &lt;enumeration value="Demanding Party"/>
 *     &lt;enumeration value="Department of Motor Vehicles"/>
 *     &lt;enumeration value="Distributor"/>
 *     &lt;enumeration value="District"/>
 *     &lt;enumeration value="Driver"/>
 *     &lt;enumeration value="Emergency Service Provider"/>
 *     &lt;enumeration value="Employee"/>
 *     &lt;enumeration value="Employer"/>
 *     &lt;enumeration value="Executor"/>
 *     &lt;enumeration value="Expert"/>
 *     &lt;enumeration value="Fire Department"/>
 *     &lt;enumeration value="Fireman"/>
 *     &lt;enumeration value="Franchise"/>
 *     &lt;enumeration value="General Contractor"/>
 *     &lt;enumeration value="Government Agency"/>
 *     &lt;enumeration value="Government Representative"/>
 *     &lt;enumeration value="Guaranteed Repair Contractor"/>
 *     &lt;enumeration value="Guardian"/>
 *     &lt;enumeration value="Injured Party"/>
 *     &lt;enumeration value="Insurance Carrier"/>
 *     &lt;enumeration value="Insured"/>
 *     &lt;enumeration value="Internal Vendor ID"/>
 *     &lt;enumeration value="Interpreter"/>
 *     &lt;enumeration value="Lienholder"/>
 *     &lt;enumeration value="Loss Payee"/>
 *     &lt;enumeration value="Manufacturer"/>
 *     &lt;enumeration value="Mediation Services"/>
 *     &lt;enumeration value="Mediator"/>
 *     &lt;enumeration value="Medical Facility"/>
 *     &lt;enumeration value="Medical Provider"/>
 *     &lt;enumeration value="Municipality"/>
 *     &lt;enumeration value="National Highway Traffic Association"/>
 *     &lt;enumeration value="Network"/>
 *     &lt;enumeration value="Occupant"/>
 *     &lt;enumeration value="Other"/>
 *     &lt;enumeration value="Owner"/>
 *     &lt;enumeration value="Owner of Property"/>
 *     &lt;enumeration value="Owner of Vehicle"/>
 *     &lt;enumeration value="Parent"/>
 *     &lt;enumeration value="Parts Broker"/>
 *     &lt;enumeration value="Pedestrian"/>
 *     &lt;enumeration value="Person to be Surveyed"/>
 *     &lt;enumeration value="Police Department"/>
 *     &lt;enumeration value="Police Officer"/>
 *     &lt;enumeration value="Policy Holder"/>
 *     &lt;enumeration value="Power of Attorney"/>
 *     &lt;enumeration value="Region"/>
 *     &lt;enumeration value="Rental Company"/>
 *     &lt;enumeration value="Rental Manager"/>
 *     &lt;enumeration value="Renter"/>
 *     &lt;enumeration value="Repair Facility"/>
 *     &lt;enumeration value="Responsible Party"/>
 *     &lt;enumeration value="Service Provider"/>
 *     &lt;enumeration value="Sub-Contractor"/>
 *     &lt;enumeration value="Subrogation Current Contact"/>
 *     &lt;enumeration value="Surveyed Person"/>
 *     &lt;enumeration value="Tenant"/>
 *     &lt;enumeration value="Title Recipient"/>
 *     &lt;enumeration value="Trustee"/>
 *     &lt;enumeration value="Vendor Code"/>
 *     &lt;enumeration value="Witness"/>
 *     &lt;enumeration value="Zone"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "PartyTypeClosedEnumType")
@XmlEnum
public enum PartyTypeClosedEnumType {

    @XmlEnumValue("Adjuster")
    ADJUSTER("Adjuster"),
    @XmlEnumValue("Administrator of an Estate")
    ADMINISTRATOR_OF_AN_ESTATE("Administrator of an Estate"),
    @XmlEnumValue("Agent")
    AGENT("Agent"),
    @XmlEnumValue("Alternate Person to be Surveyed")
    ALTERNATE_PERSON_TO_BE_SURVEYED("Alternate Person to be Surveyed"),
    @XmlEnumValue("Arbitration Services")
    ARBITRATION_SERVICES("Arbitration Services"),
    @XmlEnumValue("Arbitrator")
    ARBITRATOR("Arbitrator"),
    @XmlEnumValue("Attorney")
    ATTORNEY("Attorney"),
    @XmlEnumValue("Bid Contact")
    BID_CONTACT("Bid Contact"),
    @XmlEnumValue("Bid Source")
    BID_SOURCE("Bid Source"),
    @XmlEnumValue("Claimant")
    CLAIMANT("Claimant"),
    @XmlEnumValue("Coast Guard")
    COAST_GUARD("Coast Guard"),
    @XmlEnumValue("Consolidator")
    CONSOLIDATOR("Consolidator"),
    @XmlEnumValue("Consumer Product Safety Commission")
    CONSUMER_PRODUCT_SAFETY_COMMISSION("Consumer Product Safety Commission"),
    @XmlEnumValue("Contract Business")
    CONTRACT_BUSINESS("Contract Business"),
    @XmlEnumValue("Corporate")
    CORPORATE("Corporate"),
    @XmlEnumValue("Corporate Owned")
    CORPORATE_OWNED("Corporate Owned"),
    @XmlEnumValue("Court Assigned Representative")
    COURT_ASSIGNED_REPRESENTATIVE("Court Assigned Representative"),
    @XmlEnumValue("Court Official")
    COURT_OFFICIAL("Court Official"),
    @XmlEnumValue("Demanding Party")
    DEMANDING_PARTY("Demanding Party"),
    @XmlEnumValue("Department of Motor Vehicles")
    DEPARTMENT_OF_MOTOR_VEHICLES("Department of Motor Vehicles"),
    @XmlEnumValue("Distributor")
    DISTRIBUTOR("Distributor"),
    @XmlEnumValue("District")
    DISTRICT("District"),
    @XmlEnumValue("Driver")
    DRIVER("Driver"),
    @XmlEnumValue("Emergency Service Provider")
    EMERGENCY_SERVICE_PROVIDER("Emergency Service Provider"),
    @XmlEnumValue("Employee")
    EMPLOYEE("Employee"),
    @XmlEnumValue("Employer")
    EMPLOYER("Employer"),
    @XmlEnumValue("Executor")
    EXECUTOR("Executor"),
    @XmlEnumValue("Expert")
    EXPERT("Expert"),
    @XmlEnumValue("Fire Department")
    FIRE_DEPARTMENT("Fire Department"),
    @XmlEnumValue("Fireman")
    FIREMAN("Fireman"),
    @XmlEnumValue("Franchise")
    FRANCHISE("Franchise"),
    @XmlEnumValue("General Contractor")
    GENERAL_CONTRACTOR("General Contractor"),
    @XmlEnumValue("Government Agency")
    GOVERNMENT_AGENCY("Government Agency"),
    @XmlEnumValue("Government Representative")
    GOVERNMENT_REPRESENTATIVE("Government Representative"),
    @XmlEnumValue("Guaranteed Repair Contractor")
    GUARANTEED_REPAIR_CONTRACTOR("Guaranteed Repair Contractor"),
    @XmlEnumValue("Guardian")
    GUARDIAN("Guardian"),
    @XmlEnumValue("Injured Party")
    INJURED_PARTY("Injured Party"),
    @XmlEnumValue("Insurance Carrier")
    INSURANCE_CARRIER("Insurance Carrier"),
    @XmlEnumValue("Insured")
    INSURED("Insured"),
    @XmlEnumValue("Internal Vendor ID")
    INTERNAL_VENDOR_ID("Internal Vendor ID"),
    @XmlEnumValue("Interpreter")
    INTERPRETER("Interpreter"),
    @XmlEnumValue("Lienholder")
    LIENHOLDER("Lienholder"),
    @XmlEnumValue("Loss Payee")
    LOSS_PAYEE("Loss Payee"),
    @XmlEnumValue("Manufacturer")
    MANUFACTURER("Manufacturer"),
    @XmlEnumValue("Mediation Services")
    MEDIATION_SERVICES("Mediation Services"),
    @XmlEnumValue("Mediator")
    MEDIATOR("Mediator"),
    @XmlEnumValue("Medical Facility")
    MEDICAL_FACILITY("Medical Facility"),
    @XmlEnumValue("Medical Provider")
    MEDICAL_PROVIDER("Medical Provider"),
    @XmlEnumValue("Municipality")
    MUNICIPALITY("Municipality"),
    @XmlEnumValue("National Highway Traffic Association")
    NATIONAL_HIGHWAY_TRAFFIC_ASSOCIATION("National Highway Traffic Association"),
    @XmlEnumValue("Network")
    NETWORK("Network"),
    @XmlEnumValue("Occupant")
    OCCUPANT("Occupant"),
    @XmlEnumValue("Other")
    OTHER("Other"),
    @XmlEnumValue("Owner")
    OWNER("Owner"),
    @XmlEnumValue("Owner of Property")
    OWNER_OF_PROPERTY("Owner of Property"),
    @XmlEnumValue("Owner of Vehicle")
    OWNER_OF_VEHICLE("Owner of Vehicle"),
    @XmlEnumValue("Parent")
    PARENT("Parent"),
    @XmlEnumValue("Parts Broker")
    PARTS_BROKER("Parts Broker"),
    @XmlEnumValue("Pedestrian")
    PEDESTRIAN("Pedestrian"),
    @XmlEnumValue("Person to be Surveyed")
    PERSON_TO_BE_SURVEYED("Person to be Surveyed"),
    @XmlEnumValue("Police Department")
    POLICE_DEPARTMENT("Police Department"),
    @XmlEnumValue("Police Officer")
    POLICE_OFFICER("Police Officer"),
    @XmlEnumValue("Policy Holder")
    POLICY_HOLDER("Policy Holder"),
    @XmlEnumValue("Power of Attorney")
    POWER_OF_ATTORNEY("Power of Attorney"),
    @XmlEnumValue("Region")
    REGION("Region"),
    @XmlEnumValue("Rental Company")
    RENTAL_COMPANY("Rental Company"),
    @XmlEnumValue("Rental Manager")
    RENTAL_MANAGER("Rental Manager"),
    @XmlEnumValue("Renter")
    RENTER("Renter"),
    @XmlEnumValue("Repair Facility")
    REPAIR_FACILITY("Repair Facility"),
    @XmlEnumValue("Responsible Party")
    RESPONSIBLE_PARTY("Responsible Party"),
    @XmlEnumValue("Service Provider")
    SERVICE_PROVIDER("Service Provider"),
    @XmlEnumValue("Sub-Contractor")
    SUB_CONTRACTOR("Sub-Contractor"),
    @XmlEnumValue("Subrogation Current Contact")
    SUBROGATION_CURRENT_CONTACT("Subrogation Current Contact"),
    @XmlEnumValue("Surveyed Person")
    SURVEYED_PERSON("Surveyed Person"),
    @XmlEnumValue("Tenant")
    TENANT("Tenant"),
    @XmlEnumValue("Title Recipient")
    TITLE_RECIPIENT("Title Recipient"),
    @XmlEnumValue("Trustee")
    TRUSTEE("Trustee"),
    @XmlEnumValue("Vendor Code")
    VENDOR_CODE("Vendor Code"),
    @XmlEnumValue("Witness")
    WITNESS("Witness"),
    @XmlEnumValue("Zone")
    ZONE("Zone");
    private final String value;

    PartyTypeClosedEnumType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static PartyTypeClosedEnumType fromValue(String v) {
        for (PartyTypeClosedEnumType c: PartyTypeClosedEnumType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
