//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.03 at 12:33:26 PM PST 
//


package com.mitchell.estimate.resource.dto.lineitem;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LineItemPropertyCategoryColorClosedEnumType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="LineItemPropertyCategoryColorClosedEnumType">
 *   &lt;restriction base="{http://www.cieca.com/BMS}ClosedEnum">
 *     &lt;enumeration value="Black"/>
 *     &lt;enumeration value="Blue"/>
 *     &lt;enumeration value="Bronze"/>
 *     &lt;enumeration value="Clear"/>
 *     &lt;enumeration value="Gold"/>
 *     &lt;enumeration value="Grey"/>
 *     &lt;enumeration value="Low E"/>
 *     &lt;enumeration value="Miscellaneous"/>
 *     &lt;enumeration value="Smoked"/>
 *     &lt;enumeration value="Solar"/>
 *     &lt;enumeration value="Solex"/>
 *     &lt;enumeration value="Tinted"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "LineItemPropertyCategoryColorClosedEnumType")
@XmlEnum
public enum LineItemPropertyCategoryColorClosedEnumType {

    @XmlEnumValue("Black")
    BLACK("Black"),
    @XmlEnumValue("Blue")
    BLUE("Blue"),
    @XmlEnumValue("Bronze")
    BRONZE("Bronze"),
    @XmlEnumValue("Clear")
    CLEAR("Clear"),
    @XmlEnumValue("Gold")
    GOLD("Gold"),
    @XmlEnumValue("Grey")
    GREY("Grey"),
    @XmlEnumValue("Low E")
    LOW_E("Low E"),
    @XmlEnumValue("Miscellaneous")
    MISCELLANEOUS("Miscellaneous"),
    @XmlEnumValue("Smoked")
    SMOKED("Smoked"),
    @XmlEnumValue("Solar")
    SOLAR("Solar"),
    @XmlEnumValue("Solex")
    SOLEX("Solex"),
    @XmlEnumValue("Tinted")
    TINTED("Tinted");
    private final String value;

    LineItemPropertyCategoryColorClosedEnumType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static LineItemPropertyCategoryColorClosedEnumType fromValue(String v) {
        for (LineItemPropertyCategoryColorClosedEnumType c: LineItemPropertyCategoryColorClosedEnumType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
