//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.14 at 02:56:20 PM PST 
//


package com.mitchell.estimate.resource.entity.communication;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for InstantMessagingTypeEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="InstantMessagingTypeEnum">
 *   &lt;restriction base="{http://www.cieca.com/BMS}OpenEnum">
 *     &lt;enumeration value="AOL"/>
 *     &lt;enumeration value="ICQ"/>
 *     &lt;enumeration value="MSN"/>
 *     &lt;enumeration value="RFC2821"/>
 *     &lt;enumeration value="Yahoo"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "InstantMessagingTypeEnum")
@XmlEnum
public enum InstantMessagingTypeEnum {

    AOL("AOL"),
    ICQ("ICQ"),
    MSN("MSN"),
    @XmlEnumValue("RFC2821")
    RFC_2821("RFC2821"),
    @XmlEnumValue("Yahoo")
    YAHOO("Yahoo");
    private final String value;

    InstantMessagingTypeEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static InstantMessagingTypeEnum fromValue(String v) {
        for (InstantMessagingTypeEnum c: InstantMessagingTypeEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
