//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.03 at 12:33:26 PM PST 
//


package com.mitchell.estimate.resource.vehicle.valuation;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

import com.mitchell.estimate.resource.address.AddressType;
import com.mitchell.estimate.resource.adjustment.TotalAdjustmentInfoType;
import com.mitchell.estimate.resource.party.ContactInfoType;
import com.mitchell.estimate.resource.party.GenericPartyType;


/**
 * <p>Java class for ValuationTypeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ValuationTypeType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ValuationType" type="{http://www.cieca.com/BMS}ValuationTypeClosedEnumType"/>
 *         &lt;element name="ValuationProvider" type="{http://www.cieca.com/BMS}GenericPartyType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="ValuationRqSource" type="{http://www.cieca.com/BMS}ValuationRqSourceOpenEnumType" minOccurs="0"/>
 *         &lt;element name="ValuationLocation" type="{http://www.cieca.com/BMS}AddressType" minOccurs="0"/>
 *         &lt;element name="ValuationAdjustment" type="{http://www.cieca.com/BMS}TotalAdjustmentInfoType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="ValuationAmt" type="{http://www.cieca.com/BMS}Currency" minOccurs="0"/>
 *         &lt;element name="ValuationAmtDetails" type="{http://www.cieca.com/BMS}ValuationAmtDetailsType" minOccurs="0"/>
 *         &lt;element name="ValuationSource" type="{http://www.cieca.com/BMS}Char_80" minOccurs="0"/>
 *         &lt;element name="ListingParty" type="{http://www.cieca.com/BMS}GenericPartyType" minOccurs="0"/>
 *         &lt;element name="ListingDateTime" type="{http://www.cieca.com/BMS}DateTime" minOccurs="0"/>
 *         &lt;element name="ContactInfo" type="{http://www.cieca.com/BMS}ContactInfoType" minOccurs="0"/>
 *         &lt;element name="Submitter" type="{http://www.cieca.com/BMS}GenericPartyType" minOccurs="0"/>
 *         &lt;element name="ValuationRqArea" type="{http://www.cieca.com/BMS}ValuationRqAreaType" minOccurs="0"/>
 *         &lt;element name="ValuationDateTime" type="{http://www.cieca.com/BMS}DateTime" minOccurs="0"/>
 *         &lt;element name="ValuationReportDateTime" type="{http://www.cieca.com/BMS}DateTime" minOccurs="0"/>
 *         &lt;element name="ValuationIDNum" type="{http://www.cieca.com/BMS}Char_80" minOccurs="0"/>
 *         &lt;element name="ValuationExpirationDateTime" type="{http://www.cieca.com/BMS}DateTime" minOccurs="0"/>
 *         &lt;element name="ValuationMemo" type="{http://www.cieca.com/BMS}C" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ValuationTypeType", propOrder = {
    "valuationType",
    "valuationProvider",
    "valuationRqSource",
    "valuationLocation",
    "valuationAdjustment",
    "valuationAmt",
    "valuationAmtDetails",
    "valuationSource",
    "listingParty",
    "listingDateTime",
    "contactInfo",
    "submitter",
    "valuationRqArea",
    "valuationDateTime",
    "valuationReportDateTime",
    "valuationIDNum",
    "valuationExpirationDateTime",
    "valuationMemo"
})
public class ValuationTypeType
    implements Serializable
{

    private final static long serialVersionUID = 20120730L;
    @XmlElement(name = "ValuationType", required = true)
    protected ValuationTypeClosedEnumType valuationType;
    @XmlElement(name = "ValuationProvider")
    protected List<GenericPartyType> valuationProvider;
    @XmlElement(name = "ValuationRqSource")
    protected ValuationRqSourceOpenEnumType valuationRqSource;
    @XmlElement(name = "ValuationLocation")
    protected AddressType valuationLocation;
    @XmlElement(name = "ValuationAdjustment")
    protected List<TotalAdjustmentInfoType> valuationAdjustment;
    @XmlElement(name = "ValuationAmt")
    protected BigDecimal valuationAmt;
    @XmlElement(name = "ValuationAmtDetails")
    protected ValuationAmtDetailsType valuationAmtDetails;
    @XmlElement(name = "ValuationSource")
    protected String valuationSource;
    @XmlElement(name = "ListingParty")
    protected GenericPartyType listingParty;
    @XmlElement(name = "ListingDateTime")
    protected XMLGregorianCalendar listingDateTime;
    @XmlElement(name = "ContactInfo")
    protected ContactInfoType contactInfo;
    @XmlElement(name = "Submitter")
    protected GenericPartyType submitter;
    @XmlElement(name = "ValuationRqArea")
    protected ValuationRqAreaType valuationRqArea;
    @XmlElement(name = "ValuationDateTime")
    protected XMLGregorianCalendar valuationDateTime;
    @XmlElement(name = "ValuationReportDateTime")
    protected XMLGregorianCalendar valuationReportDateTime;
    @XmlElement(name = "ValuationIDNum")
    protected String valuationIDNum;
    @XmlElement(name = "ValuationExpirationDateTime")
    protected XMLGregorianCalendar valuationExpirationDateTime;
    @XmlElement(name = "ValuationMemo")
    protected String valuationMemo;

    /**
     * Gets the value of the valuationType property.
     * 
     * @return
     *     possible object is
     *     {@link ValuationTypeClosedEnumType }
     *     
     */
    public ValuationTypeClosedEnumType getValuationType() {
        return valuationType;
    }

    /**
     * Sets the value of the valuationType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ValuationTypeClosedEnumType }
     *     
     */
    public void setValuationType(ValuationTypeClosedEnumType value) {
        this.valuationType = value;
    }

    /**
     * Gets the value of the valuationProvider property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the valuationProvider property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getValuationProvider().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link GenericPartyType }
     * 
     * 
     */
    public List<GenericPartyType> getValuationProvider() {
        if (valuationProvider == null) {
            valuationProvider = new ArrayList<GenericPartyType>();
        }
        return this.valuationProvider;
    }

    /**
     * Gets the value of the valuationRqSource property.
     * 
     * @return
     *     possible object is
     *     {@link ValuationRqSourceOpenEnumType }
     *     
     */
    public ValuationRqSourceOpenEnumType getValuationRqSource() {
        return valuationRqSource;
    }

    /**
     * Sets the value of the valuationRqSource property.
     * 
     * @param value
     *     allowed object is
     *     {@link ValuationRqSourceOpenEnumType }
     *     
     */
    public void setValuationRqSource(ValuationRqSourceOpenEnumType value) {
        this.valuationRqSource = value;
    }

    /**
     * Gets the value of the valuationLocation property.
     * 
     * @return
     *     possible object is
     *     {@link AddressType }
     *     
     */
    public AddressType getValuationLocation() {
        return valuationLocation;
    }

    /**
     * Sets the value of the valuationLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddressType }
     *     
     */
    public void setValuationLocation(AddressType value) {
        this.valuationLocation = value;
    }

    /**
     * Gets the value of the valuationAdjustment property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the valuationAdjustment property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getValuationAdjustment().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TotalAdjustmentInfoType }
     * 
     * 
     */
    public List<TotalAdjustmentInfoType> getValuationAdjustment() {
        if (valuationAdjustment == null) {
            valuationAdjustment = new ArrayList<TotalAdjustmentInfoType>();
        }
        return this.valuationAdjustment;
    }

    /**
     * Gets the value of the valuationAmt property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getValuationAmt() {
        return valuationAmt;
    }

    /**
     * Sets the value of the valuationAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setValuationAmt(BigDecimal value) {
        this.valuationAmt = value;
    }

    /**
     * Gets the value of the valuationAmtDetails property.
     * 
     * @return
     *     possible object is
     *     {@link ValuationAmtDetailsType }
     *     
     */
    public ValuationAmtDetailsType getValuationAmtDetails() {
        return valuationAmtDetails;
    }

    /**
     * Sets the value of the valuationAmtDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link ValuationAmtDetailsType }
     *     
     */
    public void setValuationAmtDetails(ValuationAmtDetailsType value) {
        this.valuationAmtDetails = value;
    }

    /**
     * Gets the value of the valuationSource property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValuationSource() {
        return valuationSource;
    }

    /**
     * Sets the value of the valuationSource property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValuationSource(String value) {
        this.valuationSource = value;
    }

    /**
     * Gets the value of the listingParty property.
     * 
     * @return
     *     possible object is
     *     {@link GenericPartyType }
     *     
     */
    public GenericPartyType getListingParty() {
        return listingParty;
    }

    /**
     * Sets the value of the listingParty property.
     * 
     * @param value
     *     allowed object is
     *     {@link GenericPartyType }
     *     
     */
    public void setListingParty(GenericPartyType value) {
        this.listingParty = value;
    }

    /**
     * Gets the value of the listingDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getListingDateTime() {
        return listingDateTime;
    }

    /**
     * Sets the value of the listingDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setListingDateTime(XMLGregorianCalendar value) {
        this.listingDateTime = value;
    }

    /**
     * Gets the value of the contactInfo property.
     * 
     * @return
     *     possible object is
     *     {@link ContactInfoType }
     *     
     */
    public ContactInfoType getContactInfo() {
        return contactInfo;
    }

    /**
     * Sets the value of the contactInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContactInfoType }
     *     
     */
    public void setContactInfo(ContactInfoType value) {
        this.contactInfo = value;
    }

    /**
     * Gets the value of the submitter property.
     * 
     * @return
     *     possible object is
     *     {@link GenericPartyType }
     *     
     */
    public GenericPartyType getSubmitter() {
        return submitter;
    }

    /**
     * Sets the value of the submitter property.
     * 
     * @param value
     *     allowed object is
     *     {@link GenericPartyType }
     *     
     */
    public void setSubmitter(GenericPartyType value) {
        this.submitter = value;
    }

    /**
     * Gets the value of the valuationRqArea property.
     * 
     * @return
     *     possible object is
     *     {@link ValuationRqAreaType }
     *     
     */
    public ValuationRqAreaType getValuationRqArea() {
        return valuationRqArea;
    }

    /**
     * Sets the value of the valuationRqArea property.
     * 
     * @param value
     *     allowed object is
     *     {@link ValuationRqAreaType }
     *     
     */
    public void setValuationRqArea(ValuationRqAreaType value) {
        this.valuationRqArea = value;
    }

    /**
     * Gets the value of the valuationDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getValuationDateTime() {
        return valuationDateTime;
    }

    /**
     * Sets the value of the valuationDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setValuationDateTime(XMLGregorianCalendar value) {
        this.valuationDateTime = value;
    }

    /**
     * Gets the value of the valuationReportDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getValuationReportDateTime() {
        return valuationReportDateTime;
    }

    /**
     * Sets the value of the valuationReportDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setValuationReportDateTime(XMLGregorianCalendar value) {
        this.valuationReportDateTime = value;
    }

    /**
     * Gets the value of the valuationIDNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValuationIDNum() {
        return valuationIDNum;
    }

    /**
     * Sets the value of the valuationIDNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValuationIDNum(String value) {
        this.valuationIDNum = value;
    }

    /**
     * Gets the value of the valuationExpirationDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getValuationExpirationDateTime() {
        return valuationExpirationDateTime;
    }

    /**
     * Sets the value of the valuationExpirationDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setValuationExpirationDateTime(XMLGregorianCalendar value) {
        this.valuationExpirationDateTime = value;
    }

    /**
     * Gets the value of the valuationMemo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValuationMemo() {
        return valuationMemo;
    }

    /**
     * Sets the value of the valuationMemo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValuationMemo(String value) {
        this.valuationMemo = value;
    }

}
