//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.03 at 12:33:26 PM PST 
//


package com.mitchell.estimate.resource.damage;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for WhoPaysClosedEnumType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="WhoPaysClosedEnumType">
 *   &lt;restriction base="{http://www.cieca.com/BMS}ClosedEnum">
 *     &lt;enumeration value="BP"/>
 *     &lt;enumeration value="C"/>
 *     &lt;enumeration value="CP"/>
 *     &lt;enumeration value="DS"/>
 *     &lt;enumeration value="F"/>
 *     &lt;enumeration value="I"/>
 *     &lt;enumeration value="IC"/>
 *     &lt;enumeration value="IN"/>
 *     &lt;enumeration value="O"/>
 *     &lt;enumeration value="TP"/>
 *     &lt;enumeration value="W"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "WhoPaysClosedEnumType")
@XmlEnum
public enum WhoPaysClosedEnumType {

    BP,
    C,
    CP,
    DS,
    F,
    I,
    IC,
    IN,
    O,
    TP,
    W;

    public String value() {
        return name();
    }

    public static WhoPaysClosedEnumType fromValue(String v) {
        return valueOf(v);
    }

}
