//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.03 at 12:33:26 PM PST 
//


package com.mitchell.estimate.resource.vehicle.description;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

import com.mitchell.estimate.resource.address.CountryCodeOpenEnumType;
import com.mitchell.estimate.resource.parts.PartsTypeType;
import com.mitchell.estimate.resource.vehicle.power.OptionsType;

/**
 * <p>Java class for VehicleDescType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VehicleDescType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ProductionDate" type="{http://www.cieca.com/BMS}YrMon" minOccurs="0"/>
 *         &lt;element name="ManufacturerCountryCode" type="{http://www.cieca.com/BMS}CountryCodeOpenEnumType" minOccurs="0"/>
 *         &lt;element name="ModelYear" type="{http://www.cieca.com/BMS}Year" minOccurs="0"/>
 *         &lt;element name="MakeCode" type="{http://www.cieca.com/BMS}Char_4" minOccurs="0"/>
 *         &lt;element name="MakeDesc" type="{http://www.cieca.com/BMS}Char_30" minOccurs="0"/>
 *         &lt;element name="ModelNum" type="{http://www.cieca.com/BMS}Char_30" minOccurs="0"/>
 *         &lt;element name="ModelName" type="{http://www.cieca.com/BMS}Char_50" minOccurs="0"/>
 *         &lt;element name="SubModelDesc" type="{http://www.cieca.com/BMS}Char_30" minOccurs="0"/>
 *         &lt;element name="VehicleType" type="{http://www.cieca.com/BMS}VehicleTypeClosedEnumType" minOccurs="0"/>
 *         &lt;element name="OdometerInfo" type="{http://www.cieca.com/BMS}OdometerInfoType" minOccurs="0"/>
 *         &lt;element name="Package" type="{http://www.cieca.com/BMS}Char_30" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="VehicleEdition" type="{http://www.cieca.com/BMS}Char_128" minOccurs="0"/>
 *         &lt;element name="VehicleOptions" type="{http://www.cieca.com/BMS}OptionsType" minOccurs="0"/>
 *         &lt;element name="DatabaseCode" type="{http://www.cieca.com/BMS}Char_10" minOccurs="0"/>
 *         &lt;element name="DatabaseVehicleNum" type="{http://www.cieca.com/BMS}Char_10" minOccurs="0"/>
 *         &lt;element name="VehicleDescMemo" type="{http://www.cieca.com/BMS}C" minOccurs="0"/>
 *         &lt;element name="NICBInfo" type="{http://www.cieca.com/BMS}NICBInfoType" minOccurs="0"/>
 *         &lt;element name="KeysAvailableInd" type="{http://www.cieca.com/BMS}Indicator" minOccurs="0"/>
 *         &lt;element name="KeysLocationDesc" type="{http://www.cieca.com/BMS}Char_50" minOccurs="0"/>
 *         &lt;element name="Parts" type="{http://www.cieca.com/BMS}PartsTypeType" minOccurs="0"/>
 *         &lt;element name="VehicleClass" type="{http://www.cieca.com/BMS}VehicleClassOpenEnumType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="SpecialtyVehicleDesc" type="{http://www.cieca.com/BMS}SpecialtyVehicleDescType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VehicleDescType", propOrder = {
    "productionDate",
    "manufacturerCountryCode",
    "modelYear",
    "makeCode",
    "makeDesc",
    "modelNum",
    "modelName",
    "subModelDesc",
    "vehicleType",
    "odometerInfo",
    "_package",
    "vehicleEdition",
    "vehicleOptions",
    "databaseCode",
    "databaseVehicleNum",
    "vehicleDescMemo",
    "nicbInfo",
    "keysAvailableInd",
    "keysLocationDesc",
    "parts",
    "vehicleClass",
    "specialtyVehicleDesc"
})
public class VehicleDescType
    implements Serializable
{

    private final static long serialVersionUID = 20120730L;
    @XmlElement(name = "ProductionDate")
    protected XMLGregorianCalendar productionDate;
    @XmlElement(name = "ManufacturerCountryCode")
    protected CountryCodeOpenEnumType manufacturerCountryCode;
    @XmlElement(name = "ModelYear")
    protected XMLGregorianCalendar modelYear;
    @XmlElement(name = "MakeCode")
    protected String makeCode;
    @XmlElement(name = "MakeDesc")
    protected String makeDesc;
    @XmlElement(name = "ModelNum")
    protected String modelNum;
    @XmlElement(name = "ModelName")
    protected String modelName;
    @XmlElement(name = "SubModelDesc")
    protected String subModelDesc;
    @XmlElement(name = "VehicleType")
    protected VehicleTypeClosedEnumType vehicleType;
    @XmlElement(name = "OdometerInfo")
    protected OdometerInfoType odometerInfo;
    @XmlElement(name = "Package")
    protected List<String> _package;
    @XmlElement(name = "VehicleEdition")
    protected String vehicleEdition;
    @XmlElement(name = "VehicleOptions")
    protected OptionsType vehicleOptions;
    @XmlElement(name = "DatabaseCode")
    protected String databaseCode;
    @XmlElement(name = "DatabaseVehicleNum")
    protected String databaseVehicleNum;
    @XmlElement(name = "VehicleDescMemo")
    protected String vehicleDescMemo;
    @XmlElement(name = "NICBInfo")
    protected NICBInfoType nicbInfo;
    @XmlElement(name = "KeysAvailableInd")
    protected String keysAvailableInd;
    @XmlElement(name = "KeysLocationDesc")
    protected String keysLocationDesc;
    @XmlElement(name = "Parts")
    protected PartsTypeType parts;
    @XmlElement(name = "VehicleClass")
    protected List<VehicleClassOpenEnumMitchellERACRestrictionsType> vehicleClass;
    @XmlElement(name = "SpecialtyVehicleDesc")
    protected SpecialtyVehicleDescType specialtyVehicleDesc;

    /**
     * Gets the value of the productionDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getProductionDate() {
        return productionDate;
    }

    /**
     * Sets the value of the productionDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setProductionDate(XMLGregorianCalendar value) {
        this.productionDate = value;
    }

    /**
     * Gets the value of the manufacturerCountryCode property.
     * 
     * @return
     *     possible object is
     *     {@link CountryCodeOpenEnumType }
     *     
     */
    public CountryCodeOpenEnumType getManufacturerCountryCode() {
        return manufacturerCountryCode;
    }

    /**
     * Sets the value of the manufacturerCountryCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link CountryCodeOpenEnumType }
     *     
     */
    public void setManufacturerCountryCode(CountryCodeOpenEnumType value) {
        this.manufacturerCountryCode = value;
    }

    /**
     * Gets the value of the modelYear property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getModelYear() {
        return modelYear;
    }

    /**
     * Sets the value of the modelYear property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setModelYear(XMLGregorianCalendar value) {
        this.modelYear = value;
    }

    /**
     * Gets the value of the makeCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMakeCode() {
        return makeCode;
    }

    /**
     * Sets the value of the makeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMakeCode(String value) {
        this.makeCode = value;
    }

    /**
     * Gets the value of the makeDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMakeDesc() {
        return makeDesc;
    }

    /**
     * Sets the value of the makeDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMakeDesc(String value) {
        this.makeDesc = value;
    }

    /**
     * Gets the value of the modelNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModelNum() {
        return modelNum;
    }

    /**
     * Sets the value of the modelNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModelNum(String value) {
        this.modelNum = value;
    }

    /**
     * Gets the value of the modelName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModelName() {
        return modelName;
    }

    /**
     * Sets the value of the modelName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModelName(String value) {
        this.modelName = value;
    }

    /**
     * Gets the value of the subModelDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubModelDesc() {
        return subModelDesc;
    }

    /**
     * Sets the value of the subModelDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubModelDesc(String value) {
        this.subModelDesc = value;
    }

    /**
     * Gets the value of the vehicleType property.
     * 
     * @return
     *     possible object is
     *     {@link VehicleTypeClosedEnumType }
     *     
     */
    public VehicleTypeClosedEnumType getVehicleType() {
        return vehicleType;
    }

    /**
     * Sets the value of the vehicleType property.
     * 
     * @param value
     *     allowed object is
     *     {@link VehicleTypeClosedEnumType }
     *     
     */
    public void setVehicleType(VehicleTypeClosedEnumType value) {
        this.vehicleType = value;
    }

    /**
     * Gets the value of the odometerInfo property.
     * 
     * @return
     *     possible object is
     *     {@link OdometerInfoType }
     *     
     */
    public OdometerInfoType getOdometerInfo() {
        return odometerInfo;
    }

    /**
     * Sets the value of the odometerInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link OdometerInfoType }
     *     
     */
    public void setOdometerInfo(OdometerInfoType value) {
        this.odometerInfo = value;
    }

    /**
     * Gets the value of the package property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the package property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPackage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getPackage() {
        if (_package == null) {
            _package = new ArrayList<String>();
        }
        return this._package;
    }

    /**
     * Gets the value of the vehicleEdition property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVehicleEdition() {
        return vehicleEdition;
    }

    /**
     * Sets the value of the vehicleEdition property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVehicleEdition(String value) {
        this.vehicleEdition = value;
    }

    /**
     * Gets the value of the vehicleOptions property.
     * 
     * @return
     *     possible object is
     *     {@link OptionsType }
     *     
     */
    public OptionsType getVehicleOptions() {
        return vehicleOptions;
    }

    /**
     * Sets the value of the vehicleOptions property.
     * 
     * @param value
     *     allowed object is
     *     {@link OptionsType }
     *     
     */
    public void setVehicleOptions(OptionsType value) {
        this.vehicleOptions = value;
    }

    /**
     * Gets the value of the databaseCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDatabaseCode() {
        return databaseCode;
    }

    /**
     * Sets the value of the databaseCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDatabaseCode(String value) {
        this.databaseCode = value;
    }

    /**
     * Gets the value of the databaseVehicleNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDatabaseVehicleNum() {
        return databaseVehicleNum;
    }

    /**
     * Sets the value of the databaseVehicleNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDatabaseVehicleNum(String value) {
        this.databaseVehicleNum = value;
    }

    /**
     * Gets the value of the vehicleDescMemo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVehicleDescMemo() {
        return vehicleDescMemo;
    }

    /**
     * Sets the value of the vehicleDescMemo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVehicleDescMemo(String value) {
        this.vehicleDescMemo = value;
    }

    /**
     * Gets the value of the nicbInfo property.
     * 
     * @return
     *     possible object is
     *     {@link NICBInfoType }
     *     
     */
    public NICBInfoType getNICBInfo() {
        return nicbInfo;
    }

    /**
     * Sets the value of the nicbInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link NICBInfoType }
     *     
     */
    public void setNICBInfo(NICBInfoType value) {
        this.nicbInfo = value;
    }

    /**
     * Gets the value of the keysAvailableInd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKeysAvailableInd() {
        return keysAvailableInd;
    }

    /**
     * Sets the value of the keysAvailableInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKeysAvailableInd(String value) {
        this.keysAvailableInd = value;
    }

    /**
     * Gets the value of the keysLocationDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKeysLocationDesc() {
        return keysLocationDesc;
    }

    /**
     * Sets the value of the keysLocationDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKeysLocationDesc(String value) {
        this.keysLocationDesc = value;
    }

    /**
     * Gets the value of the parts property.
     * 
     * @return
     *     possible object is
     *     {@link PartsTypeType }
     *     
     */
    public PartsTypeType getParts() {
        return parts;
    }

    /**
     * Sets the value of the parts property.
     * 
     * @param value
     *     allowed object is
     *     {@link PartsTypeType }
     *     
     */
    public void setParts(PartsTypeType value) {
        this.parts = value;
    }

    /**
     * Gets the value of the vehicleClass property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the vehicleClass property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getVehicleClass().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link VehicleClassOpenEnumMitchellERACRestrictionsType }
     * 
     * 
     */
    public List<VehicleClassOpenEnumMitchellERACRestrictionsType> getVehicleClass() {
        if (vehicleClass == null) {
            vehicleClass = new ArrayList<VehicleClassOpenEnumMitchellERACRestrictionsType>();
        }
        return this.vehicleClass;
    }

    /**
     * Gets the value of the specialtyVehicleDesc property.
     * 
     * @return
     *     possible object is
     *     {@link SpecialtyVehicleDescType }
     *     
     */
    public SpecialtyVehicleDescType getSpecialtyVehicleDesc() {
        return specialtyVehicleDesc;
    }

    /**
     * Sets the value of the specialtyVehicleDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link SpecialtyVehicleDescType }
     *     
     */
    public void setSpecialtyVehicleDesc(SpecialtyVehicleDescType value) {
        this.specialtyVehicleDesc = value;
    }

}
