//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.03 at 12:33:26 PM PST 
//


package com.mitchell.estimate.resource.vehicle.description;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for VehicleTypeClosedEnumType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="VehicleTypeClosedEnumType">
 *   &lt;restriction base="{http://www.cieca.com/BMS}ClosedEnum">
 *     &lt;enumeration value="AT"/>
 *     &lt;enumeration value="BV"/>
 *     &lt;enumeration value="CO"/>
 *     &lt;enumeration value="FD"/>
 *     &lt;enumeration value="FM"/>
 *     &lt;enumeration value="HE"/>
 *     &lt;enumeration value="HT"/>
 *     &lt;enumeration value="LD"/>
 *     &lt;enumeration value="MC"/>
 *     &lt;enumeration value="MP"/>
 *     &lt;enumeration value="MT"/>
 *     &lt;enumeration value="OL"/>
 *     &lt;enumeration value="PC"/>
 *     &lt;enumeration value="PW"/>
 *     &lt;enumeration value="RA"/>
 *     &lt;enumeration value="RC"/>
 *     &lt;enumeration value="RU"/>
 *     &lt;enumeration value="RV"/>
 *     &lt;enumeration value="S1"/>
 *     &lt;enumeration value="SC"/>
 *     &lt;enumeration value="SN"/>
 *     &lt;enumeration value="ST"/>
 *     &lt;enumeration value="SU"/>
 *     &lt;enumeration value="SV"/>
 *     &lt;enumeration value="TK"/>
 *     &lt;enumeration value="TL"/>
 *     &lt;enumeration value="TP"/>
 *     &lt;enumeration value="TR"/>
 *     &lt;enumeration value="TX"/>
 *     &lt;enumeration value="UV"/>
 *     &lt;enumeration value="VN"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "VehicleTypeClosedEnumType")
@XmlEnum
public enum VehicleTypeClosedEnumType {

    AT("AT"),
    BV("BV"),
    CO("CO"),
    FD("FD"),
    FM("FM"),
    HE("HE"),
    HT("HT"),
    LD("LD"),
    MC("MC"),
    MP("MP"),
    MT("MT"),
    OL("OL"),
    PC("PC"),
    PW("PW"),
    RA("RA"),
    RC("RC"),
    RU("RU"),
    RV("RV"),
    @XmlEnumValue("S1")
    S_1("S1"),
    SC("SC"),
    SN("SN"),
    ST("ST"),
    SU("SU"),
    SV("SV"),
    TK("TK"),
    TL("TL"),
    TP("TP"),
    TR("TR"),
    TX("TX"),
    UV("UV"),
    VN("VN");
    private final String value;

    VehicleTypeClosedEnumType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static VehicleTypeClosedEnumType fromValue(String v) {
        for (VehicleTypeClosedEnumType c: VehicleTypeClosedEnumType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
