//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.03 at 12:33:26 PM PST 
//


package com.mitchell.estimate.resource.service.dto.vehicle.valuation;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ValuationTypeClosedEnumType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ValuationTypeClosedEnumType">
 *   &lt;restriction base="{http://www.cieca.com/BMS}ClosedEnum">
 *     &lt;enumeration value="ACV"/>
 *     &lt;enumeration value="BAS"/>
 *     &lt;enumeration value="BID"/>
 *     &lt;enumeration value="BKV"/>
 *     &lt;enumeration value="BLK"/>
 *     &lt;enumeration value="BLUE"/>
 *     &lt;enumeration value="CLST"/>
 *     &lt;enumeration value="COMP"/>
 *     &lt;enumeration value="DLRQ"/>
 *     &lt;enumeration value="DSCN"/>
 *     &lt;enumeration value="DSCR"/>
 *     &lt;enumeration value="DSNR"/>
 *     &lt;enumeration value="ESV"/>
 *     &lt;enumeration value="GSV"/>
 *     &lt;enumeration value="MSRP"/>
 *     &lt;enumeration value="NADA"/>
 *     &lt;enumeration value="RDBK"/>
 *     &lt;enumeration value="SPEC"/>
 *     &lt;enumeration value="VIR"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ValuationTypeClosedEnumType")
@XmlEnum
public enum ValuationTypeClosedEnumType {

    ACV,
    BAS,
    BID,
    BKV,
    BLK,
    BLUE,
    CLST,
    COMP,
    DLRQ,
    DSCN,
    DSCR,
    DSNR,
    ESV,
    GSV,
    MSRP,
    NADA,
    RDBK,
    SPEC,
    VIR;

    public String value() {
        return name();
    }

    public static ValuationTypeClosedEnumType fromValue(String v) {
        return valueOf(v);
    }

}
