//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.03 at 12:33:26 PM PST 
//


package com.mitchell.estimate.resource.document;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for VendorCodeOpenEnumType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="VendorCodeOpenEnumType">
 *   &lt;restriction base="{http://www.cieca.com/BMS}OpenEnum">
 *     &lt;enumeration value="A"/>
 *     &lt;enumeration value="APU"/>
 *     &lt;enumeration value="AutoQuote"/>
 *     &lt;enumeration value="AutoWatch"/>
 *     &lt;enumeration value="C"/>
 *     &lt;enumeration value="Car-Part.com"/>
 *     &lt;enumeration value="ComSearch"/>
 *     &lt;enumeration value="D"/>
 *     &lt;enumeration value="Dupont"/>
 *     &lt;enumeration value="E"/>
 *     &lt;enumeration value="GTM"/>
 *     &lt;enumeration value="Hollander"/>
 *     &lt;enumeration value="HyperQuest"/>
 *     &lt;enumeration value="ITS"/>
 *     &lt;enumeration value="Jhenn Systems Inc"/>
 *     &lt;enumeration value="M"/>
 *     &lt;enumeration value="New Era"/>
 *     &lt;enumeration value="Norgate"/>
 *     &lt;enumeration value="O"/>
 *     &lt;enumeration value="Parts Trader"/>
 *     &lt;enumeration value="PartsHotlines"/>
 *     &lt;enumeration value="Pinnacle/URG"/>
 *     &lt;enumeration value="Real Parts"/>
 *     &lt;enumeration value="ROME"/>
 *     &lt;enumeration value="Summit"/>
 *     &lt;enumeration value="UPart"/>
 *     &lt;enumeration value="URG/Pinnacle"/>
 *     &lt;enumeration value="Web-Est LLC"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "VendorCodeOpenEnumType")
@XmlEnum
public enum VendorCodeOpenEnumType {

    A("A"),
    APU("APU"),
    @XmlEnumValue("AutoQuote")
    AUTO_QUOTE("AutoQuote"),
    @XmlEnumValue("AutoWatch")
    AUTO_WATCH("AutoWatch"),
    C("C"),
    @XmlEnumValue("Car-Part.com")
    CAR_PART_COM("Car-Part.com"),
    @XmlEnumValue("ComSearch")
    COM_SEARCH("ComSearch"),
    D("D"),
    @XmlEnumValue("Dupont")
    DUPONT("Dupont"),
    E("E"),
    GTM("GTM"),
    @XmlEnumValue("Hollander")
    HOLLANDER("Hollander"),
    @XmlEnumValue("HyperQuest")
    HYPER_QUEST("HyperQuest"),
    ITS("ITS"),
    @XmlEnumValue("Jhenn Systems Inc")
    JHENN_SYSTEMS_INC("Jhenn Systems Inc"),
    M("M"),
    @XmlEnumValue("New Era")
    NEW_ERA("New Era"),
    @XmlEnumValue("Norgate")
    NORGATE("Norgate"),
    O("O"),
    @XmlEnumValue("Parts Trader")
    PARTS_TRADER("Parts Trader"),
    @XmlEnumValue("PartsHotlines")
    PARTS_HOTLINES("PartsHotlines"),
    @XmlEnumValue("Pinnacle/URG")
    PINNACLE_URG("Pinnacle/URG"),
    @XmlEnumValue("Real Parts")
    REAL_PARTS("Real Parts"),
    ROME("ROME"),
    @XmlEnumValue("Summit")
    SUMMIT("Summit"),
    @XmlEnumValue("UPart")
    U_PART("UPart"),
    @XmlEnumValue("URG/Pinnacle")
    URG_PINNACLE("URG/Pinnacle"),
    @XmlEnumValue("Web-Est LLC")
    WEB_EST_LLC("Web-Est LLC");
    private final String value;

    VendorCodeOpenEnumType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static VendorCodeOpenEnumType fromValue(String v) {
        for (VendorCodeOpenEnumType c: VendorCodeOpenEnumType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
