//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.03 at 12:33:26 PM PST 
//


package com.mitchell.estimate.resource.dto.loss;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DamageSeverityClosedEnumType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="DamageSeverityClosedEnumType">
 *   &lt;restriction base="{http://www.cieca.com/BMS}ClosedEnum">
 *     &lt;enumeration value="Minor"/>
 *     &lt;enumeration value="Moderate"/>
 *     &lt;enumeration value="None"/>
 *     &lt;enumeration value="Severe"/>
 *     &lt;enumeration value="Unknown"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "DamageSeverityClosedEnumType")
@XmlEnum
public enum DamageSeverityClosedEnumType {

    @XmlEnumValue("Minor")
    MINOR("Minor"),
    @XmlEnumValue("Moderate")
    MODERATE("Moderate"),
    @XmlEnumValue("None")
    NONE("None"),
    @XmlEnumValue("Severe")
    SEVERE("Severe"),
    @XmlEnumValue("Unknown")
    UNKNOWN("Unknown");
    private final String value;

    DamageSeverityClosedEnumType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static DamageSeverityClosedEnumType fromValue(String v) {
        for (DamageSeverityClosedEnumType c: DamageSeverityClosedEnumType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
