//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.04 at 02:43:16 PM PST 
//


package com.mitchell.estimate.resource.service.dto.parts;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RateTypeClosedEnumBaseType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="RateTypeClosedEnumBaseType">
 *   &lt;restriction base="{http://www.cieca.com/BMS}ClosedEnum">
 *     &lt;enumeration value="ALL"/>
 *     &lt;enumeration value="BE"/>
 *     &lt;enumeration value="BEAC"/>
 *     &lt;enumeration value="BELA"/>
 *     &lt;enumeration value="BELP"/>
 *     &lt;enumeration value="BEPA"/>
 *     &lt;enumeration value="BEPL"/>
 *     &lt;enumeration value="BEPM"/>
 *     &lt;enumeration value="BEPO"/>
 *     &lt;enumeration value="BEPP"/>
 *     &lt;enumeration value="BESL"/>
 *     &lt;enumeration value="BETP"/>
 *     &lt;enumeration value="LA"/>
 *     &lt;enumeration value="LA1"/>
 *     &lt;enumeration value="LA2"/>
 *     &lt;enumeration value="LA2S"/>
 *     &lt;enumeration value="LA2U"/>
 *     &lt;enumeration value="LA3"/>
 *     &lt;enumeration value="LA3S"/>
 *     &lt;enumeration value="LA4"/>
 *     &lt;enumeration value="LAB"/>
 *     &lt;enumeration value="LABA"/>
 *     &lt;enumeration value="LABS"/>
 *     &lt;enumeration value="LACG"/>
 *     &lt;enumeration value="LAD"/>
 *     &lt;enumeration value="LADT"/>
 *     &lt;enumeration value="LAE"/>
 *     &lt;enumeration value="LAE2"/>
 *     &lt;enumeration value="LAET"/>
 *     &lt;enumeration value="LAF"/>
 *     &lt;enumeration value="LAFA"/>
 *     &lt;enumeration value="LAFS"/>
 *     &lt;enumeration value="LAG"/>
 *     &lt;enumeration value="LAGA"/>
 *     &lt;enumeration value="LAGS"/>
 *     &lt;enumeration value="LAM"/>
 *     &lt;enumeration value="LAMA"/>
 *     &lt;enumeration value="LAMS"/>
 *     &lt;enumeration value="LAP"/>
 *     &lt;enumeration value="LAR"/>
 *     &lt;enumeration value="LARA"/>
 *     &lt;enumeration value="LARS"/>
 *     &lt;enumeration value="LAS"/>
 *     &lt;enumeration value="LASA"/>
 *     &lt;enumeration value="LASS"/>
 *     &lt;enumeration value="LASU"/>
 *     &lt;enumeration value="LAT"/>
 *     &lt;enumeration value="LATT"/>
 *     &lt;enumeration value="LAU"/>
 *     &lt;enumeration value="LAUT"/>
 *     &lt;enumeration value="MA2S"/>
 *     &lt;enumeration value="MA2T"/>
 *     &lt;enumeration value="MA3S"/>
 *     &lt;enumeration value="MABL"/>
 *     &lt;enumeration value="MACS"/>
 *     &lt;enumeration value="MAFP"/>
 *     &lt;enumeration value="MAHW"/>
 *     &lt;enumeration value="MAPA"/>
 *     &lt;enumeration value="MASH"/>
 *     &lt;enumeration value="MASP"/>
 *     &lt;enumeration value="MAT"/>
 *     &lt;enumeration value="MATD"/>
 *     &lt;enumeration value="OT1"/>
 *     &lt;enumeration value="OT2"/>
 *     &lt;enumeration value="OT3"/>
 *     &lt;enumeration value="OT4"/>
 *     &lt;enumeration value="OTA"/>
 *     &lt;enumeration value="OTAC"/>
 *     &lt;enumeration value="OTBE"/>
 *     &lt;enumeration value="OTCO"/>
 *     &lt;enumeration value="OTDE"/>
 *     &lt;enumeration value="OTEC"/>
 *     &lt;enumeration value="OTFO"/>
 *     &lt;enumeration value="OTGL"/>
 *     &lt;enumeration value="OTLU"/>
 *     &lt;enumeration value="OTP"/>
 *     &lt;enumeration value="OTRC"/>
 *     &lt;enumeration value="OTSH"/>
 *     &lt;enumeration value="OTSI"/>
 *     &lt;enumeration value="OTSL"/>
 *     &lt;enumeration value="OTSP"/>
 *     &lt;enumeration value="OTST"/>
 *     &lt;enumeration value="OTTL"/>
 *     &lt;enumeration value="OTTR"/>
 *     &lt;enumeration value="OTTW"/>
 *     &lt;enumeration value="PA"/>
 *     &lt;enumeration value="PAA"/>
 *     &lt;enumeration value="PAC"/>
 *     &lt;enumeration value="PAE"/>
 *     &lt;enumeration value="PAG"/>
 *     &lt;enumeration value="PAGD"/>
 *     &lt;enumeration value="PAGF"/>
 *     &lt;enumeration value="PAGP"/>
 *     &lt;enumeration value="PAGQ"/>
 *     &lt;enumeration value="PAGR"/>
 *     &lt;enumeration value="PAL"/>
 *     &lt;enumeration value="PAM"/>
 *     &lt;enumeration value="PAN"/>
 *     &lt;enumeration value="PAO"/>
 *     &lt;enumeration value="PAP"/>
 *     &lt;enumeration value="PAR"/>
 *     &lt;enumeration value="PASL"/>
 *     &lt;enumeration value="PAT"/>
 *     &lt;enumeration value="PAX1"/>
 *     &lt;enumeration value="PAX2"/>
 *     &lt;enumeration value="PAX3"/>
 *     &lt;enumeration value="REFT"/>
 *     &lt;enumeration value="TOT"/>
 *     &lt;enumeration value="ATS"/>

 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "RateTypeClosedEnumType")
@XmlEnum
public enum RateTypeClosedEnumType {

    ALL("ALL"),
    BE("BE"),
    BEAC("BEAC"),
    BELA("BELA"),
    BELP("BELP"),
    BEPA("BEPA"),
    BEPL("BEPL"),
    BEPM("BEPM"),
    BEPO("BEPO"),
    BEPP("BEPP"),
    BESL("BESL"),
    BETP("BETP"),
    LA("LA"),
    @XmlEnumValue("LA1")
    LA_1("LA1"),
    @XmlEnumValue("LA2")
    LA_2("LA2"),
    @XmlEnumValue("LA2S")
    LA_2_S("LA2S"),
    @XmlEnumValue("LA2U")
    LA_2_U("LA2U"),
    @XmlEnumValue("LA3")
    LA_3("LA3"),
    @XmlEnumValue("LA3S")
    LA_3_S("LA3S"),
    @XmlEnumValue("LA4")
    LA_4("LA4"),
    LAB("LAB"),
    LABA("LABA"),
    LABS("LABS"),
    LACG("LACG"),
    LAD("LAD"),
    LADT("LADT"),
    LAE("LAE"),
    @XmlEnumValue("LAE2")
    LAE_2("LAE2"),
    LAET("LAET"),
    LAF("LAF"),
    LAFA("LAFA"),
    LAFS("LAFS"),
    LAG("LAG"),
    LAGA("LAGA"),
    LAGS("LAGS"),
    LAM("LAM"),
    LAMA("LAMA"),
    LAMS("LAMS"),
    LAP("LAP"),
    LAR("LAR"),
    LARA("LARA"),
    LARS("LARS"),
    LAS("LAS"),
    LASA("LASA"),
    LASS("LASS"),
    LASU("LASU"),
    LAT("LAT"),
    LATT("LATT"),
    LAU("LAU"),
    LAUT("LAUT"),
    @XmlEnumValue("MA2S")
    MA_2_S("MA2S"),
    @XmlEnumValue("MA2T")
    MA_2_T("MA2T"),
    @XmlEnumValue("MA3S")
    MA_3_S("MA3S"),
    MABL("MABL"),
    MACS("MACS"),
    MAFP("MAFP"),
    MAHW("MAHW"),
    MAPA("MAPA"),
    MASH("MASH"),
    MASP("MASP"),
    MAT("MAT"),
    MATD("MATD"),
    @XmlEnumValue("OT1")
    OT_1("OT1"),
    @XmlEnumValue("OT2")
    OT_2("OT2"),
    @XmlEnumValue("OT3")
    OT_3("OT3"),
    @XmlEnumValue("OT4")
    OT_4("OT4"),
    OTA("OTA"),
    OTAC("OTAC"),
    OTBE("OTBE"),
    OTCO("OTCO"),
    OTDE("OTDE"),
    OTEC("OTEC"),
    OTFO("OTFO"),
    OTGL("OTGL"),
    OTLU("OTLU"),
    OTP("OTP"),
    OTRC("OTRC"),
    OTSH("OTSH"),
    OTSI("OTSI"),
    OTSL("OTSL"),
    OTSP("OTSP"),
    OTST("OTST"),
    OTTL("OTTL"),
    OTTR("OTTR"),
    OTTW("OTTW"),
    PA("PA"),
    PAA("PAA"),
    PAC("PAC"),
    PAE("PAE"),
    PAG("PAG"),
    PAGD("PAGD"),
    PAGF("PAGF"),
    PAGP("PAGP"),
    PAGQ("PAGQ"),
    PAGR("PAGR"),
    PAL("PAL"),
    PAM("PAM"),
    PAN("PAN"),
    PAO("PAO"),
    PAP("PAP"),
    PAR("PAR"),
    PASL("PASL"),
    PAT("PAT"),
    @XmlEnumValue("PAX1")
    PAX_1("PAX1"),
    @XmlEnumValue("PAX2")
    PAX_2("PAX2"),
    @XmlEnumValue("PAX3")
    PAX_3("PAX3"),
    REFT("REFT"),
    TOT("TOT"),
    ATS("ATS");
    private final String value;

    RateTypeClosedEnumType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static RateTypeClosedEnumType fromValue(String v) {
        for (RateTypeClosedEnumType c: RateTypeClosedEnumType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
