//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.03 at 12:33:26 PM PST 
//


package com.mitchell.estimate.resource.vehicle.tire;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlType;

import com.mitchell.estimate.resource.vehicle.UnitOfMeasureClosedEnumType;

/**
 * <p>Java class for TireInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TireInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TireMfg" type="{http://www.cieca.com/BMS}Char_80" minOccurs="0"/>
 *         &lt;element name="TireSizeDesc" type="{http://www.cieca.com/BMS}Char_80" minOccurs="0"/>
 *         &lt;element name="TireType" type="{http://www.cieca.com/BMS}TireTypeOpenEnumType" minOccurs="0"/>
 *         &lt;element name="TirePosition" type="{http://www.cieca.com/BMS}TirePositionOpenEnumType"/>
 *         &lt;choice>
 *           &lt;sequence>
 *             &lt;element name="TreadDepth" type="{http://www.cieca.com/BMS}Decimal_Range_0-200.0000"/>
 *             &lt;element name="WearRange" type="{http://www.cieca.com/BMS}WearRangeType" minOccurs="0"/>
 *           &lt;/sequence>
 *           &lt;element name="WearRange" type="{http://www.cieca.com/BMS}WearRangeType"/>
 *         &lt;/choice>
 *         &lt;element name="UnitOfMeasure" type="{http://www.cieca.com/BMS}UnitOfMeasureClosedEnumType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TireInfoType", propOrder = {
    "content"
})
public class TireInfoType
    implements Serializable
{

    private final static long serialVersionUID = 20120730L;
    @XmlElementRefs({
        @XmlElementRef(name = "TirePosition", namespace = "http://www.cieca.com/BMS", type = JAXBElement.class),
        @XmlElementRef(name = "TireSizeDesc", namespace = "http://www.cieca.com/BMS", type = JAXBElement.class),
        @XmlElementRef(name = "TreadDepth", namespace = "http://www.cieca.com/BMS", type = JAXBElement.class),
        @XmlElementRef(name = "TireMfg", namespace = "http://www.cieca.com/BMS", type = JAXBElement.class),
        @XmlElementRef(name = "WearRange", namespace = "http://www.cieca.com/BMS", type = JAXBElement.class),
        @XmlElementRef(name = "UnitOfMeasure", namespace = "http://www.cieca.com/BMS", type = JAXBElement.class),
        @XmlElementRef(name = "TireType", namespace = "http://www.cieca.com/BMS", type = JAXBElement.class)
    })
    protected List<JAXBElement<?>> content;

    /**
     * Gets the rest of the content model. 
     * 
     * <p>
     * You are getting this "catch-all" property because of the following reason: 
     * The field name "WearRange" is used by two different parts of a schema. See: 
     * line 1754 of file:/C:/Users/pm104238/tfs/CommonXMLSchema/master/common-xml-schema/src/main/xsd/CIECA_BMS/v5.1.1_strictBMSCodeExtSchemas/BMSCommonGlobalTypes_CodeExt_2015-04-14.xsd
     * line 1752 of file:/C:/Users/pm104238/tfs/CommonXMLSchema/master/common-xml-schema/src/main/xsd/CIECA_BMS/v5.1.1_strictBMSCodeExtSchemas/BMSCommonGlobalTypes_CodeExt_2015-04-14.xsd
     * <p>
     * To get rid of this property, apply a property customization to one 
     * of both of the following declarations to change their names: 
     * Gets the value of the content property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the content property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link TirePositionOpenEnumType }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link WearRangeType }{@code >}
     * {@link JAXBElement }{@code <}{@link UnitOfMeasureClosedEnumType }{@code >}
     * {@link JAXBElement }{@code <}{@link TireTypeOpenEnumType }{@code >}
     * 
     * 
     */
    public List<JAXBElement<?>> getContent() {
        if (content == null) {
            content = new ArrayList<JAXBElement<?>>();
        }
        return this.content;
    }

}
