//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.03 at 12:33:26 PM PST 
//


package com.mitchell.estimate.resource.vehicle.tire;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TireTypeOpenEnumType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TireTypeOpenEnumType">
 *   &lt;restriction base="{http://www.cieca.com/BMS}OpenEnum">
 *     &lt;enumeration value="Agricultural"/>
 *     &lt;enumeration value="All Season"/>
 *     &lt;enumeration value="All-terrain"/>
 *     &lt;enumeration value="Bias"/>
 *     &lt;enumeration value="Mud"/>
 *     &lt;enumeration value="Off Road"/>
 *     &lt;enumeration value="Performance"/>
 *     &lt;enumeration value="Radial"/>
 *     &lt;enumeration value="Retread"/>
 *     &lt;enumeration value="Run Flat"/>
 *     &lt;enumeration value="Snow"/>
 *     &lt;enumeration value="Snow Studded"/>
 *     &lt;enumeration value="Sport Street"/>
 *     &lt;enumeration value="Sport Touring"/>
 *     &lt;enumeration value="Steel Belted"/>
 *     &lt;enumeration value="Whitewall"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "TireTypeOpenEnumType")
@XmlEnum
public enum TireTypeOpenEnumType {

    @XmlEnumValue("Agricultural")
    AGRICULTURAL("Agricultural"),
    @XmlEnumValue("All Season")
    ALL_SEASON("All Season"),
    @XmlEnumValue("All-terrain")
    ALL_TERRAIN("All-terrain"),
    @XmlEnumValue("Bias")
    BIAS("Bias"),
    @XmlEnumValue("Mud")
    MUD("Mud"),
    @XmlEnumValue("Off Road")
    OFF_ROAD("Off Road"),
    @XmlEnumValue("Performance")
    PERFORMANCE("Performance"),
    @XmlEnumValue("Radial")
    RADIAL("Radial"),
    @XmlEnumValue("Retread")
    RETREAD("Retread"),
    @XmlEnumValue("Run Flat")
    RUN_FLAT("Run Flat"),
    @XmlEnumValue("Snow")
    SNOW("Snow"),
    @XmlEnumValue("Snow Studded")
    SNOW_STUDDED("Snow Studded"),
    @XmlEnumValue("Sport Street")
    SPORT_STREET("Sport Street"),
    @XmlEnumValue("Sport Touring")
    SPORT_TOURING("Sport Touring"),
    @XmlEnumValue("Steel Belted")
    STEEL_BELTED("Steel Belted"),
    @XmlEnumValue("Whitewall")
    WHITEWALL("Whitewall");
    private final String value;

    TireTypeOpenEnumType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TireTypeOpenEnumType fromValue(String v) {
        for (TireTypeOpenEnumType c: TireTypeOpenEnumType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
