//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.03 at 12:33:26 PM PST 
//


package com.mitchell.estimate.resource.service.dto.vehicle.vin;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for VINDecodeStatusClosedEnumType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="VINDecodeStatusClosedEnumType">
 *   &lt;restriction base="{http://www.cieca.com/BMS}ClosedEnum">
 *     &lt;enumeration value="Check Digit Error"/>
 *     &lt;enumeration value="Decode Errors"/>
 *     &lt;enumeration value="Does Not Decode"/>
 *     &lt;enumeration value="Gray Market"/>
 *     &lt;enumeration value="Incorrect Length"/>
 *     &lt;enumeration value="Not Evaluated"/>
 *     &lt;enumeration value="Partial Decode"/>
 *     &lt;enumeration value="Wrong Vehicle"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "VINDecodeStatusClosedEnumType")
@XmlEnum
public enum VINDecodeStatusClosedEnumType {

    @XmlEnumValue("Check Digit Error")
    CHECK_DIGIT_ERROR("Check Digit Error"),
    @XmlEnumValue("Decode Errors")
    DECODE_ERRORS("Decode Errors"),
    @XmlEnumValue("Does Not Decode")
    DOES_NOT_DECODE("Does Not Decode"),
    @XmlEnumValue("Gray Market")
    GRAY_MARKET("Gray Market"),
    @XmlEnumValue("Incorrect Length")
    INCORRECT_LENGTH("Incorrect Length"),
    @XmlEnumValue("Not Evaluated")
    NOT_EVALUATED("Not Evaluated"),
    @XmlEnumValue("Partial Decode")
    PARTIAL_DECODE("Partial Decode"),
    @XmlEnumValue("Wrong Vehicle")
    WRONG_VEHICLE("Wrong Vehicle");
    private final String value;

    VINDecodeStatusClosedEnumType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static VINDecodeStatusClosedEnumType fromValue(String v) {
        for (VINDecodeStatusClosedEnumType c: VINDecodeStatusClosedEnumType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
