//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.03 at 12:33:26 PM PST 
//


package com.mitchell.estimate.resource.admin;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import com.mitchell.estimate.resource.party.AccompanyingPartyType;
import com.mitchell.estimate.resource.party.CancellationPartyType;
import com.mitchell.estimate.resource.party.DemandingPartyType;
import com.mitchell.estimate.resource.party.GenericLocationSiteType;
import com.mitchell.estimate.resource.party.GenericPartyType;
import com.mitchell.estimate.resource.party.OtherPartyType;
import com.mitchell.estimate.resource.party.RepresentativePartyType;
import com.mitchell.estimate.resource.party.ResponsiblePartyType;


/**
 * <p>Java class for AdminInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AdminInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="InsuranceCompany" type="{http://www.cieca.com/BMS}InsuranceCompanyType" minOccurs="0"/>
 *         &lt;element name="ClaimOffice" type="{http://www.cieca.com/BMS}ClaimOfficeType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="InsuranceAgent" type="{http://www.cieca.com/BMS}GenericPartyType" minOccurs="0"/>
 *         &lt;element name="PolicyHolder" type="{http://www.cieca.com/BMS}PolicyHolderType" minOccurs="0"/>
 *         &lt;element name="Insured" type="{http://www.cieca.com/BMS}GenericPartyType" minOccurs="0"/>
 *         &lt;element name="Owner" type="{http://www.cieca.com/BMS}GenericPartyType" minOccurs="0"/>
 *         &lt;element name="Customer" type="{http://www.cieca.com/BMS}GenericPartyType" minOccurs="0"/>
 *         &lt;element name="Beneficiary" type="{http://www.cieca.com/BMS}GenericPartyType" minOccurs="0"/>
 *         &lt;element name="Lienholder" type="{http://www.cieca.com/BMS}LienholderType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Claimant" type="{http://www.cieca.com/BMS}ClaimantType" minOccurs="0"/>
 *         &lt;element name="Estimator" type="{http://www.cieca.com/BMS}EstimatorType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="InspectionSite" type="{http://www.cieca.com/BMS}GenericPartyType" minOccurs="0"/>
 *         &lt;element name="RepairFacility" type="{http://www.cieca.com/BMS}RepairFacilityType" minOccurs="0"/>
 *         &lt;element name="VehicleLocationSite" type="{http://www.cieca.com/BMS}GenericPartyType" minOccurs="0"/>
 *         &lt;element name="LossLocationSite" type="{http://www.cieca.com/BMS}GenericPartyType" minOccurs="0"/>
 *         &lt;element name="InitialPickUpLocationSite" type="{http://www.cieca.com/BMS}GenericLocationSiteType" minOccurs="0"/>
 *         &lt;element name="DestinationLocationSite" type="{http://www.cieca.com/BMS}GenericLocationSiteType" minOccurs="0"/>
 *         &lt;element name="CustomerLocationSite" type="{http://www.cieca.com/BMS}GenericLocationSiteType" minOccurs="0"/>
 *         &lt;element name="AppointmentLocationSite" type="{http://www.cieca.com/BMS}GenericLocationSiteType" minOccurs="0"/>
 *         &lt;element name="Consolidator" type="{http://www.cieca.com/BMS}GenericPartyType" minOccurs="0"/>
 *         &lt;element name="Adjuster" type="{http://www.cieca.com/BMS}AdjusterType" minOccurs="0"/>
 *         &lt;element name="Supplier" type="{http://www.cieca.com/BMS}GenericPartyType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="ThirdPartyAdministrator" type="{http://www.cieca.com/BMS}ThirdPartyAdministratorType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Renter" type="{http://www.cieca.com/BMS}RenterType" minOccurs="0"/>
 *         &lt;element name="AlternateInsurer" type="{http://www.cieca.com/BMS}GenericPartyType" minOccurs="0"/>
 *         &lt;element name="GAPProvider" type="{http://www.cieca.com/BMS}GAPProviderType" minOccurs="0"/>
 *         &lt;element name="Receiver" type="{http://www.cieca.com/BMS}GenericPartyType" minOccurs="0"/>
 *         &lt;element name="Forwarder" type="{http://www.cieca.com/BMS}GenericPartyType" minOccurs="0"/>
 *         &lt;element name="Sender" type="{http://www.cieca.com/BMS}GenericPartyType" minOccurs="0"/>
 *         &lt;element name="Submitter" type="{http://www.cieca.com/BMS}GenericPartyType" minOccurs="0"/>
 *         &lt;element name="RentalCarCompany" type="{http://www.cieca.com/BMS}GenericPartyType" minOccurs="0"/>
 *         &lt;element name="RentalOffice" type="{http://www.cieca.com/BMS}GenericPartyType" minOccurs="0"/>
 *         &lt;element name="GovernmentAgency" type="{http://www.cieca.com/BMS}GenericLocationSiteType" minOccurs="0"/>
 *         &lt;element name="ProcessDelay" type="{http://www.cieca.com/BMS}ProcessDelayType" minOccurs="0"/>
 *         &lt;element name="CancellationParty" type="{http://www.cieca.com/BMS}CancellationPartyType" minOccurs="0"/>
 *         &lt;element name="FleetCompany" type="{http://www.cieca.com/BMS}GenericPartyType" minOccurs="0"/>
 *         &lt;element name="Driver" type="{http://www.cieca.com/BMS}GenericPartyType" minOccurs="0"/>
 *         &lt;element name="OtherParty" type="{http://www.cieca.com/BMS}OtherPartyType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="DemandingParty" type="{http://www.cieca.com/BMS}DemandingPartyType" minOccurs="0"/>
 *         &lt;element name="ResponsibleParty" type="{http://www.cieca.com/BMS}ResponsiblePartyType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="RepresentativeParty" type="{http://www.cieca.com/BMS}RepresentativePartyType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="AccompanyingParty" type="{http://www.cieca.com/BMS}AccompanyingPartyType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="SubrogationVendor" type="{http://www.cieca.com/BMS}GenericPartyType" minOccurs="0"/>
 *         &lt;element name="InvestigativeVendor" type="{http://www.cieca.com/BMS}GenericPartyType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="PartyOfInterest" type="{http://www.cieca.com/BMS}GenericPartyType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Subcontractor" type="{http://www.cieca.com/BMS}GenericPartyType" minOccurs="0"/>
 *         &lt;element name="InformationProvider" type="{http://www.cieca.com/BMS}GenericPartyType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="TowCompany" type="{http://www.cieca.com/BMS}GenericPartyType" minOccurs="0"/>
 *         &lt;element name="TowDispatcher" type="{http://www.cieca.com/BMS}GenericPartyType" minOccurs="0"/>
 *         &lt;element name="TowRequestor" type="{http://www.cieca.com/BMS}GenericPartyType" minOccurs="0"/>
 *         &lt;element name="Broker" type="{http://www.cieca.com/BMS}GenericPartyType" minOccurs="0"/>
 *         &lt;element name="ArbitrationRepresentative" type="{http://www.cieca.com/BMS}GenericPartyType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="AlternativeDisputeResolutionServiceProvider" type="{http://www.cieca.com/BMS}GenericPartyType" minOccurs="0"/>
 *         &lt;element name="EliminatedResponsibleParty" type="{http://www.cieca.com/BMS}GenericPartyType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="AdditionalResponsibleParty" type="{http://www.cieca.com/BMS}GenericPartyType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Salvor" type="{http://www.cieca.com/BMS}GenericPartyType" minOccurs="0"/>
 *         &lt;element name="SalvageProvider" type="{http://www.cieca.com/BMS}GenericPartyType" minOccurs="0"/>
 *         &lt;element name="VehicleResaleProvider" type="{http://www.cieca.com/BMS}GenericPartyType" minOccurs="0"/>
 *         &lt;element name="BillToParty" type="{http://www.cieca.com/BMS}GenericPartyType" minOccurs="0"/>
 *         &lt;element name="RemitToParty" type="{http://www.cieca.com/BMS}GenericPartyType" minOccurs="0"/>
 *         &lt;element name="ServiceProvider" type="{http://www.cieca.com/BMS}GenericPartyType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AdminInfoType", propOrder = {
    "insuranceCompany",
    "claimOffice",
    "insuranceAgent",
    "policyHolder",
    "insured",
    "owner",
    "customer",
    "beneficiary",
    "lienholder",
    "claimant",
    "estimator",
    "inspectionSite",
    "repairFacility",
    "vehicleLocationSite",
    "lossLocationSite",
    "initialPickUpLocationSite",
    "destinationLocationSite",
    "customerLocationSite",
    "appointmentLocationSite",
    "consolidator",
    "adjuster",
    "supplier",
    "thirdPartyAdministrator",
    "renter",
    "alternateInsurer",
    "gapProvider",
    "receiver",
    "forwarder",
    "sender",
    "submitter",
    "rentalCarCompany",
    "rentalOffice",
    "governmentAgency",
    "processDelay",
    "cancellationParty",
    "fleetCompany",
    "driver",
    "otherParty",
    "demandingParty",
    "responsibleParty",
    "representativeParty",
    "accompanyingParty",
    "subrogationVendor",
    "investigativeVendor",
    "partyOfInterest",
    "subcontractor",
    "informationProvider",
    "towCompany",
    "towDispatcher",
    "towRequestor",
    "broker",
    "arbitrationRepresentative",
    "alternativeDisputeResolutionServiceProvider",
    "eliminatedResponsibleParty",
    "additionalResponsibleParty",
    "salvor",
    "salvageProvider",
    "vehicleResaleProvider",
    "billToParty",
    "remitToParty",
    "serviceProvider"
})
public class AdminInfoType implements Serializable
{

    private final static long serialVersionUID = 20120730L;
    @XmlElement(name = "InsuranceCompany")
    protected InsuranceCompanyType insuranceCompany;
    @XmlElement(name = "ClaimOffice")
    protected List<ClaimOfficeType> claimOffice;
    @XmlElement(name = "InsuranceAgent")
    protected GenericPartyType insuranceAgent;
    @XmlElement(name = "PolicyHolder")
    protected PolicyHolderType policyHolder;
    @XmlElement(name = "Insured")
    protected GenericPartyType insured;
    @XmlElement(name = "Owner")
    protected GenericPartyType owner;
    @XmlElement(name = "Customer")
    protected GenericPartyType customer;
    @XmlElement(name = "Beneficiary")
    protected GenericPartyType beneficiary;
    @XmlElement(name = "Lienholder")
    protected List<LienholderType> lienholder;
    @XmlElement(name = "Claimant")
    protected ClaimantType claimant;
    @XmlElement(name = "Estimator")
    protected List<EstimatorType> estimator;
    @XmlElement(name = "InspectionSite")
    protected GenericPartyType inspectionSite;
    @XmlElement(name = "RepairFacility")
    protected RepairFacilityType repairFacility;
    @XmlElement(name = "VehicleLocationSite")
    protected GenericPartyType vehicleLocationSite;
    @XmlElement(name = "LossLocationSite")
    protected GenericPartyType lossLocationSite;
    @XmlElement(name = "InitialPickUpLocationSite")
    protected GenericLocationSiteType initialPickUpLocationSite;
    @XmlElement(name = "DestinationLocationSite")
    protected GenericLocationSiteType destinationLocationSite;
    @XmlElement(name = "CustomerLocationSite")
    protected GenericLocationSiteType customerLocationSite;
    @XmlElement(name = "AppointmentLocationSite")
    protected GenericLocationSiteType appointmentLocationSite;
    @XmlElement(name = "Consolidator")
    protected GenericPartyType consolidator;
    @XmlElement(name = "Adjuster")
    protected AdjusterType adjuster;
    @XmlElement(name = "Supplier")
    protected List<GenericPartyType> supplier;
    @XmlElement(name = "ThirdPartyAdministrator")
    protected List<ThirdPartyAdministratorType> thirdPartyAdministrator;
    @XmlElement(name = "Renter")
    protected RenterType renter;
    @XmlElement(name = "AlternateInsurer")
    protected GenericPartyType alternateInsurer;
    @XmlElement(name = "GAPProvider")
    protected GAPProviderType gapProvider;
    @XmlElement(name = "Receiver")
    protected GenericPartyType receiver;
    @XmlElement(name = "Forwarder")
    protected GenericPartyType forwarder;
    @XmlElement(name = "Sender")
    protected GenericPartyType sender;
    @XmlElement(name = "Submitter")
    protected GenericPartyType submitter;
    @XmlElement(name = "RentalCarCompany")
    protected GenericPartyType rentalCarCompany;
    @XmlElement(name = "RentalOffice")
    protected GenericPartyType rentalOffice;
    @XmlElement(name = "GovernmentAgency")
    protected GenericLocationSiteType governmentAgency;
    @XmlElement(name = "ProcessDelay")
    protected ProcessDelayType processDelay;
    @XmlElement(name = "CancellationParty")
    protected CancellationPartyType cancellationParty;
    @XmlElement(name = "FleetCompany")
    protected GenericPartyType fleetCompany;
    @XmlElement(name = "Driver")
    protected GenericPartyType driver;
    @XmlElement(name = "OtherParty")
    protected List<OtherPartyType> otherParty;
    @XmlElement(name = "DemandingParty")
    protected DemandingPartyType demandingParty;
    @XmlElement(name = "ResponsibleParty")
    protected List<ResponsiblePartyType> responsibleParty;
    @XmlElement(name = "RepresentativeParty")
    protected List<RepresentativePartyType> representativeParty;
    @XmlElement(name = "AccompanyingParty")
    protected List<AccompanyingPartyType> accompanyingParty;
    @XmlElement(name = "SubrogationVendor")
    protected GenericPartyType subrogationVendor;
    @XmlElement(name = "InvestigativeVendor")
    protected List<GenericPartyType> investigativeVendor;
    @XmlElement(name = "PartyOfInterest")
    protected List<GenericPartyType> partyOfInterest;
    @XmlElement(name = "Subcontractor")
    protected GenericPartyType subcontractor;
    @XmlElement(name = "InformationProvider")
    protected List<GenericPartyType> informationProvider;
    @XmlElement(name = "TowCompany")
    protected GenericPartyType towCompany;
    @XmlElement(name = "TowDispatcher")
    protected GenericPartyType towDispatcher;
    @XmlElement(name = "TowRequestor")
    protected GenericPartyType towRequestor;
    @XmlElement(name = "Broker")
    protected GenericPartyType broker;
    @XmlElement(name = "ArbitrationRepresentative")
    protected List<GenericPartyType> arbitrationRepresentative;
    @XmlElement(name = "AlternativeDisputeResolutionServiceProvider")
    protected GenericPartyType alternativeDisputeResolutionServiceProvider;
    @XmlElement(name = "EliminatedResponsibleParty")
    protected List<GenericPartyType> eliminatedResponsibleParty;
    @XmlElement(name = "AdditionalResponsibleParty")
    protected List<GenericPartyType> additionalResponsibleParty;
    @XmlElement(name = "Salvor")
    protected GenericPartyType salvor;
    @XmlElement(name = "SalvageProvider")
    protected GenericPartyType salvageProvider;
    @XmlElement(name = "VehicleResaleProvider")
    protected GenericPartyType vehicleResaleProvider;
    @XmlElement(name = "BillToParty")
    protected GenericPartyType billToParty;
    @XmlElement(name = "RemitToParty")
    protected GenericPartyType remitToParty;
    @XmlElement(name = "ServiceProvider")
    protected GenericPartyType serviceProvider;

    /**
     * Gets the value of the insuranceCompany property.
     * 
     * @return
     *     possible object is
     *     {@link InsuranceCompanyType }
     *     
     */
    public InsuranceCompanyType getInsuranceCompany() {
        return insuranceCompany;
    }

    /**
     * Sets the value of the insuranceCompany property.
     * 
     * @param value
     *     allowed object is
     *     {@link InsuranceCompanyType }
     *     
     */
    public void setInsuranceCompany(InsuranceCompanyType value) {
        this.insuranceCompany = value;
    }

    /**
     * Gets the value of the claimOffice property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the claimOffice property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getClaimOffice().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ClaimOfficeType }
     * 
     * 
     */
    public List<ClaimOfficeType> getClaimOffice() {
        if (claimOffice == null) {
            claimOffice = new ArrayList<ClaimOfficeType>();
        }
        return this.claimOffice;
    }

    /**
     * Gets the value of the insuranceAgent property.
     * 
     * @return
     *     possible object is
     *     {@link GenericPartyType }
     *     
     */
    public GenericPartyType getInsuranceAgent() {
        return insuranceAgent;
    }

    /**
     * Sets the value of the insuranceAgent property.
     * 
     * @param value
     *     allowed object is
     *     {@link GenericPartyType }
     *     
     */
    public void setInsuranceAgent(GenericPartyType value) {
        this.insuranceAgent = value;
    }

    /**
     * Gets the value of the policyHolder property.
     * 
     * @return
     *     possible object is
     *     {@link PolicyHolderType }
     *     
     */
    public PolicyHolderType getPolicyHolder() {
        return policyHolder;
    }

    /**
     * Sets the value of the policyHolder property.
     * 
     * @param value
     *     allowed object is
     *     {@link PolicyHolderType }
     *     
     */
    public void setPolicyHolder(PolicyHolderType value) {
        this.policyHolder = value;
    }

    /**
     * Gets the value of the insured property.
     * 
     * @return
     *     possible object is
     *     {@link GenericPartyType }
     *     
     */
    public GenericPartyType getInsured() {
        return insured;
    }

    /**
     * Sets the value of the insured property.
     * 
     * @param value
     *     allowed object is
     *     {@link GenericPartyType }
     *     
     */
    public void setInsured(GenericPartyType value) {
        this.insured = value;
    }

    /**
     * Gets the value of the owner property.
     * 
     * @return
     *     possible object is
     *     {@link GenericPartyType }
     *     
     */
    public GenericPartyType getOwner() {
        return owner;
    }

    /**
     * Sets the value of the owner property.
     * 
     * @param value
     *     allowed object is
     *     {@link GenericPartyType }
     *     
     */
    public void setOwner(GenericPartyType value) {
        this.owner = value;
    }

    /**
     * Gets the value of the customer property.
     * 
     * @return
     *     possible object is
     *     {@link GenericPartyType }
     *     
     */
    public GenericPartyType getCustomer() {
        return customer;
    }

    /**
     * Sets the value of the customer property.
     * 
     * @param value
     *     allowed object is
     *     {@link GenericPartyType }
     *     
     */
    public void setCustomer(GenericPartyType value) {
        this.customer = value;
    }

    /**
     * Gets the value of the beneficiary property.
     * 
     * @return
     *     possible object is
     *     {@link GenericPartyType }
     *     
     */
    public GenericPartyType getBeneficiary() {
        return beneficiary;
    }

    /**
     * Sets the value of the beneficiary property.
     * 
     * @param value
     *     allowed object is
     *     {@link GenericPartyType }
     *     
     */
    public void setBeneficiary(GenericPartyType value) {
        this.beneficiary = value;
    }

    /**
     * Gets the value of the lienholder property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the lienholder property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLienholder().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LienholderType }
     * 
     * 
     */
    public List<LienholderType> getLienholder() {
        if (lienholder == null) {
            lienholder = new ArrayList<LienholderType>();
        }
        return this.lienholder;
    }

    /**
     * Gets the value of the claimant property.
     * 
     * @return
     *     possible object is
     *     {@link ClaimantType }
     *     
     */
    public ClaimantType getClaimant() {
        return claimant;
    }

    /**
     * Sets the value of the claimant property.
     * 
     * @param value
     *     allowed object is
     *     {@link ClaimantType }
     *     
     */
    public void setClaimant(ClaimantType value) {
        this.claimant = value;
    }

    /**
     * Gets the value of the estimator property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the estimator property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEstimator().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EstimatorType }
     * 
     * 
     */
    public List<EstimatorType> getEstimator() {
        if (estimator == null) {
            estimator = new ArrayList<EstimatorType>();
        }
        return this.estimator;
    }

    /**
     * Gets the value of the inspectionSite property.
     * 
     * @return
     *     possible object is
     *     {@link GenericPartyType }
     *     
     */
    public GenericPartyType getInspectionSite() {
        return inspectionSite;
    }

    /**
     * Sets the value of the inspectionSite property.
     * 
     * @param value
     *     allowed object is
     *     {@link GenericPartyType }
     *     
     */
    public void setInspectionSite(GenericPartyType value) {
        this.inspectionSite = value;
    }

    /**
     * Gets the value of the repairFacility property.
     * 
     * @return
     *     possible object is
     *     {@link RepairFacilityType }
     *     
     */
    public RepairFacilityType getRepairFacility() {
        return repairFacility;
    }

    /**
     * Sets the value of the repairFacility property.
     * 
     * @param value
     *     allowed object is
     *     {@link RepairFacilityType }
     *     
     */
    public void setRepairFacility(RepairFacilityType value) {
        this.repairFacility = value;
    }

    /**
     * Gets the value of the vehicleLocationSite property.
     * 
     * @return
     *     possible object is
     *     {@link GenericPartyType }
     *     
     */
    public GenericPartyType getVehicleLocationSite() {
        return vehicleLocationSite;
    }

    /**
     * Sets the value of the vehicleLocationSite property.
     * 
     * @param value
     *     allowed object is
     *     {@link GenericPartyType }
     *     
     */
    public void setVehicleLocationSite(GenericPartyType value) {
        this.vehicleLocationSite = value;
    }

    /**
     * Gets the value of the lossLocationSite property.
     * 
     * @return
     *     possible object is
     *     {@link GenericPartyType }
     *     
     */
    public GenericPartyType getLossLocationSite() {
        return lossLocationSite;
    }

    /**
     * Sets the value of the lossLocationSite property.
     * 
     * @param value
     *     allowed object is
     *     {@link GenericPartyType }
     *     
     */
    public void setLossLocationSite(GenericPartyType value) {
        this.lossLocationSite = value;
    }

    /**
     * Gets the value of the initialPickUpLocationSite property.
     * 
     * @return
     *     possible object is
     *     {@link GenericLocationSiteType }
     *     
     */
    public GenericLocationSiteType getInitialPickUpLocationSite() {
        return initialPickUpLocationSite;
    }

    /**
     * Sets the value of the initialPickUpLocationSite property.
     * 
     * @param value
     *     allowed object is
     *     {@link GenericLocationSiteType }
     *     
     */
    public void setInitialPickUpLocationSite(GenericLocationSiteType value) {
        this.initialPickUpLocationSite = value;
    }

    /**
     * Gets the value of the destinationLocationSite property.
     * 
     * @return
     *     possible object is
     *     {@link GenericLocationSiteType }
     *     
     */
    public GenericLocationSiteType getDestinationLocationSite() {
        return destinationLocationSite;
    }

    /**
     * Sets the value of the destinationLocationSite property.
     * 
     * @param value
     *     allowed object is
     *     {@link GenericLocationSiteType }
     *     
     */
    public void setDestinationLocationSite(GenericLocationSiteType value) {
        this.destinationLocationSite = value;
    }

    /**
     * Gets the value of the customerLocationSite property.
     * 
     * @return
     *     possible object is
     *     {@link GenericLocationSiteType }
     *     
     */
    public GenericLocationSiteType getCustomerLocationSite() {
        return customerLocationSite;
    }

    /**
     * Sets the value of the customerLocationSite property.
     * 
     * @param value
     *     allowed object is
     *     {@link GenericLocationSiteType }
     *     
     */
    public void setCustomerLocationSite(GenericLocationSiteType value) {
        this.customerLocationSite = value;
    }

    /**
     * Gets the value of the appointmentLocationSite property.
     * 
     * @return
     *     possible object is
     *     {@link GenericLocationSiteType }
     *     
     */
    public GenericLocationSiteType getAppointmentLocationSite() {
        return appointmentLocationSite;
    }

    /**
     * Sets the value of the appointmentLocationSite property.
     * 
     * @param value
     *     allowed object is
     *     {@link GenericLocationSiteType }
     *     
     */
    public void setAppointmentLocationSite(GenericLocationSiteType value) {
        this.appointmentLocationSite = value;
    }

    /**
     * Gets the value of the consolidator property.
     * 
     * @return
     *     possible object is
     *     {@link GenericPartyType }
     *     
     */
    public GenericPartyType getConsolidator() {
        return consolidator;
    }

    /**
     * Sets the value of the consolidator property.
     * 
     * @param value
     *     allowed object is
     *     {@link GenericPartyType }
     *     
     */
    public void setConsolidator(GenericPartyType value) {
        this.consolidator = value;
    }

    /**
     * Gets the value of the adjuster property.
     * 
     * @return
     *     possible object is
     *     {@link AdjusterType }
     *     
     */
    public AdjusterType getAdjuster() {
        return adjuster;
    }

    /**
     * Sets the value of the adjuster property.
     * 
     * @param value
     *     allowed object is
     *     {@link AdjusterType }
     *     
     */
    public void setAdjuster(AdjusterType value) {
        this.adjuster = value;
    }

    /**
     * Gets the value of the supplier property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the supplier property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSupplier().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link GenericPartyType }
     * 
     * 
     */
    public List<GenericPartyType> getSupplier() {
        if (supplier == null) {
            supplier = new ArrayList<GenericPartyType>();
        }
        return this.supplier;
    }

    /**
     * Gets the value of the thirdPartyAdministrator property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the thirdPartyAdministrator property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getThirdPartyAdministrator().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ThirdPartyAdministratorType }
     * 
     * 
     */
    public List<ThirdPartyAdministratorType> getThirdPartyAdministrator() {
        if (thirdPartyAdministrator == null) {
            thirdPartyAdministrator = new ArrayList<ThirdPartyAdministratorType>();
        }
        return this.thirdPartyAdministrator;
    }

    /**
     * Gets the value of the renter property.
     * 
     * @return
     *     possible object is
     *     {@link RenterType }
     *     
     */
    public RenterType getRenter() {
        return renter;
    }

    /**
     * Sets the value of the renter property.
     * 
     * @param value
     *     allowed object is
     *     {@link RenterType }
     *     
     */
    public void setRenter(RenterType value) {
        this.renter = value;
    }

    /**
     * Gets the value of the alternateInsurer property.
     * 
     * @return
     *     possible object is
     *     {@link GenericPartyType }
     *     
     */
    public GenericPartyType getAlternateInsurer() {
        return alternateInsurer;
    }

    /**
     * Sets the value of the alternateInsurer property.
     * 
     * @param value
     *     allowed object is
     *     {@link GenericPartyType }
     *     
     */
    public void setAlternateInsurer(GenericPartyType value) {
        this.alternateInsurer = value;
    }

    /**
     * Gets the value of the gapProvider property.
     * 
     * @return
     *     possible object is
     *     {@link GAPProviderType }
     *     
     */
    public GAPProviderType getGAPProvider() {
        return gapProvider;
    }

    /**
     * Sets the value of the gapProvider property.
     * 
     * @param value
     *     allowed object is
     *     {@link GAPProviderType }
     *     
     */
    public void setGAPProvider(GAPProviderType value) {
        this.gapProvider = value;
    }

    /**
     * Gets the value of the receiver property.
     * 
     * @return
     *     possible object is
     *     {@link GenericPartyType }
     *     
     */
    public GenericPartyType getReceiver() {
        return receiver;
    }

    /**
     * Sets the value of the receiver property.
     * 
     * @param value
     *     allowed object is
     *     {@link GenericPartyType }
     *     
     */
    public void setReceiver(GenericPartyType value) {
        this.receiver = value;
    }

    /**
     * Gets the value of the forwarder property.
     * 
     * @return
     *     possible object is
     *     {@link GenericPartyType }
     *     
     */
    public GenericPartyType getForwarder() {
        return forwarder;
    }

    /**
     * Sets the value of the forwarder property.
     * 
     * @param value
     *     allowed object is
     *     {@link GenericPartyType }
     *     
     */
    public void setForwarder(GenericPartyType value) {
        this.forwarder = value;
    }

    /**
     * Gets the value of the sender property.
     * 
     * @return
     *     possible object is
     *     {@link GenericPartyType }
     *     
     */
    public GenericPartyType getSender() {
        return sender;
    }

    /**
     * Sets the value of the sender property.
     * 
     * @param value
     *     allowed object is
     *     {@link GenericPartyType }
     *     
     */
    public void setSender(GenericPartyType value) {
        this.sender = value;
    }

    /**
     * Gets the value of the submitter property.
     * 
     * @return
     *     possible object is
     *     {@link GenericPartyType }
     *     
     */
    public GenericPartyType getSubmitter() {
        return submitter;
    }

    /**
     * Sets the value of the submitter property.
     * 
     * @param value
     *     allowed object is
     *     {@link GenericPartyType }
     *     
     */
    public void setSubmitter(GenericPartyType value) {
        this.submitter = value;
    }

    /**
     * Gets the value of the rentalCarCompany property.
     * 
     * @return
     *     possible object is
     *     {@link GenericPartyType }
     *     
     */
    public GenericPartyType getRentalCarCompany() {
        return rentalCarCompany;
    }

    /**
     * Sets the value of the rentalCarCompany property.
     * 
     * @param value
     *     allowed object is
     *     {@link GenericPartyType }
     *     
     */
    public void setRentalCarCompany(GenericPartyType value) {
        this.rentalCarCompany = value;
    }

    /**
     * Gets the value of the rentalOffice property.
     * 
     * @return
     *     possible object is
     *     {@link GenericPartyType }
     *     
     */
    public GenericPartyType getRentalOffice() {
        return rentalOffice;
    }

    /**
     * Sets the value of the rentalOffice property.
     * 
     * @param value
     *     allowed object is
     *     {@link GenericPartyType }
     *     
     */
    public void setRentalOffice(GenericPartyType value) {
        this.rentalOffice = value;
    }

    /**
     * Gets the value of the governmentAgency property.
     * 
     * @return
     *     possible object is
     *     {@link GenericLocationSiteType }
     *     
     */
    public GenericLocationSiteType getGovernmentAgency() {
        return governmentAgency;
    }

    /**
     * Sets the value of the governmentAgency property.
     * 
     * @param value
     *     allowed object is
     *     {@link GenericLocationSiteType }
     *     
     */
    public void setGovernmentAgency(GenericLocationSiteType value) {
        this.governmentAgency = value;
    }

    /**
     * Gets the value of the processDelay property.
     * 
     * @return
     *     possible object is
     *     {@link ProcessDelayType }
     *     
     */
    public ProcessDelayType getProcessDelay() {
        return processDelay;
    }

    /**
     * Sets the value of the processDelay property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProcessDelayType }
     *     
     */
    public void setProcessDelay(ProcessDelayType value) {
        this.processDelay = value;
    }

    /**
     * Gets the value of the cancellationParty property.
     * 
     * @return
     *     possible object is
     *     {@link CancellationPartyType }
     *     
     */
    public CancellationPartyType getCancellationParty() {
        return cancellationParty;
    }

    /**
     * Sets the value of the cancellationParty property.
     * 
     * @param value
     *     allowed object is
     *     {@link CancellationPartyType }
     *     
     */
    public void setCancellationParty(CancellationPartyType value) {
        this.cancellationParty = value;
    }

    /**
     * Gets the value of the fleetCompany property.
     * 
     * @return
     *     possible object is
     *     {@link GenericPartyType }
     *     
     */
    public GenericPartyType getFleetCompany() {
        return fleetCompany;
    }

    /**
     * Sets the value of the fleetCompany property.
     * 
     * @param value
     *     allowed object is
     *     {@link GenericPartyType }
     *     
     */
    public void setFleetCompany(GenericPartyType value) {
        this.fleetCompany = value;
    }

    /**
     * Gets the value of the driver property.
     * 
     * @return
     *     possible object is
     *     {@link GenericPartyType }
     *     
     */
    public GenericPartyType getDriver() {
        return driver;
    }

    /**
     * Sets the value of the driver property.
     * 
     * @param value
     *     allowed object is
     *     {@link GenericPartyType }
     *     
     */
    public void setDriver(GenericPartyType value) {
        this.driver = value;
    }

    /**
     * Gets the value of the otherParty property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the otherParty property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOtherParty().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OtherPartyType }
     * 
     * 
     */
    public List<OtherPartyType> getOtherParty() {
        if (otherParty == null) {
            otherParty = new ArrayList<OtherPartyType>();
        }
        return this.otherParty;
    }

    /**
     * Gets the value of the demandingParty property.
     * 
     * @return
     *     possible object is
     *     {@link DemandingPartyType }
     *     
     */
    public DemandingPartyType getDemandingParty() {
        return demandingParty;
    }

    /**
     * Sets the value of the demandingParty property.
     * 
     * @param value
     *     allowed object is
     *     {@link DemandingPartyType }
     *     
     */
    public void setDemandingParty(DemandingPartyType value) {
        this.demandingParty = value;
    }

    /**
     * Gets the value of the responsibleParty property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the responsibleParty property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getResponsibleParty().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ResponsiblePartyType }
     * 
     * 
     */
    public List<ResponsiblePartyType> getResponsibleParty() {
        if (responsibleParty == null) {
            responsibleParty = new ArrayList<ResponsiblePartyType>();
        }
        return this.responsibleParty;
    }

    /**
     * Gets the value of the representativeParty property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the representativeParty property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRepresentativeParty().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RepresentativePartyType }
     * 
     * 
     */
    public List<RepresentativePartyType> getRepresentativeParty() {
        if (representativeParty == null) {
            representativeParty = new ArrayList<RepresentativePartyType>();
        }
        return this.representativeParty;
    }

    /**
     * Gets the value of the accompanyingParty property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the accompanyingParty property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAccompanyingParty().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AccompanyingPartyType }
     * 
     * 
     */
    public List<AccompanyingPartyType> getAccompanyingParty() {
        if (accompanyingParty == null) {
            accompanyingParty = new ArrayList<AccompanyingPartyType>();
        }
        return this.accompanyingParty;
    }

    /**
     * Gets the value of the subrogationVendor property.
     * 
     * @return
     *     possible object is
     *     {@link GenericPartyType }
     *     
     */
    public GenericPartyType getSubrogationVendor() {
        return subrogationVendor;
    }

    /**
     * Sets the value of the subrogationVendor property.
     * 
     * @param value
     *     allowed object is
     *     {@link GenericPartyType }
     *     
     */
    public void setSubrogationVendor(GenericPartyType value) {
        this.subrogationVendor = value;
    }

    /**
     * Gets the value of the investigativeVendor property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the investigativeVendor property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInvestigativeVendor().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link GenericPartyType }
     * 
     * 
     */
    public List<GenericPartyType> getInvestigativeVendor() {
        if (investigativeVendor == null) {
            investigativeVendor = new ArrayList<GenericPartyType>();
        }
        return this.investigativeVendor;
    }

    /**
     * Gets the value of the partyOfInterest property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the partyOfInterest property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPartyOfInterest().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link GenericPartyType }
     * 
     * 
     */
    public List<GenericPartyType> getPartyOfInterest() {
        if (partyOfInterest == null) {
            partyOfInterest = new ArrayList<GenericPartyType>();
        }
        return this.partyOfInterest;
    }

    /**
     * Gets the value of the subcontractor property.
     * 
     * @return
     *     possible object is
     *     {@link GenericPartyType }
     *     
     */
    public GenericPartyType getSubcontractor() {
        return subcontractor;
    }

    /**
     * Sets the value of the subcontractor property.
     * 
     * @param value
     *     allowed object is
     *     {@link GenericPartyType }
     *     
     */
    public void setSubcontractor(GenericPartyType value) {
        this.subcontractor = value;
    }

    /**
     * Gets the value of the informationProvider property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the informationProvider property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInformationProvider().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link GenericPartyType }
     * 
     * 
     */
    public List<GenericPartyType> getInformationProvider() {
        if (informationProvider == null) {
            informationProvider = new ArrayList<GenericPartyType>();
        }
        return this.informationProvider;
    }

    /**
     * Gets the value of the towCompany property.
     * 
     * @return
     *     possible object is
     *     {@link GenericPartyType }
     *     
     */
    public GenericPartyType getTowCompany() {
        return towCompany;
    }

    /**
     * Sets the value of the towCompany property.
     * 
     * @param value
     *     allowed object is
     *     {@link GenericPartyType }
     *     
     */
    public void setTowCompany(GenericPartyType value) {
        this.towCompany = value;
    }

    /**
     * Gets the value of the towDispatcher property.
     * 
     * @return
     *     possible object is
     *     {@link GenericPartyType }
     *     
     */
    public GenericPartyType getTowDispatcher() {
        return towDispatcher;
    }

    /**
     * Sets the value of the towDispatcher property.
     * 
     * @param value
     *     allowed object is
     *     {@link GenericPartyType }
     *     
     */
    public void setTowDispatcher(GenericPartyType value) {
        this.towDispatcher = value;
    }

    /**
     * Gets the value of the towRequestor property.
     * 
     * @return
     *     possible object is
     *     {@link GenericPartyType }
     *     
     */
    public GenericPartyType getTowRequestor() {
        return towRequestor;
    }

    /**
     * Sets the value of the towRequestor property.
     * 
     * @param value
     *     allowed object is
     *     {@link GenericPartyType }
     *     
     */
    public void setTowRequestor(GenericPartyType value) {
        this.towRequestor = value;
    }

    /**
     * Gets the value of the broker property.
     * 
     * @return
     *     possible object is
     *     {@link GenericPartyType }
     *     
     */
    public GenericPartyType getBroker() {
        return broker;
    }

    /**
     * Sets the value of the broker property.
     * 
     * @param value
     *     allowed object is
     *     {@link GenericPartyType }
     *     
     */
    public void setBroker(GenericPartyType value) {
        this.broker = value;
    }

    /**
     * Gets the value of the arbitrationRepresentative property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the arbitrationRepresentative property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getArbitrationRepresentative().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link GenericPartyType }
     * 
     * 
     */
    public List<GenericPartyType> getArbitrationRepresentative() {
        if (arbitrationRepresentative == null) {
            arbitrationRepresentative = new ArrayList<GenericPartyType>();
        }
        return this.arbitrationRepresentative;
    }

    /**
     * Gets the value of the alternativeDisputeResolutionServiceProvider property.
     * 
     * @return
     *     possible object is
     *     {@link GenericPartyType }
     *     
     */
    public GenericPartyType getAlternativeDisputeResolutionServiceProvider() {
        return alternativeDisputeResolutionServiceProvider;
    }

    /**
     * Sets the value of the alternativeDisputeResolutionServiceProvider property.
     * 
     * @param value
     *     allowed object is
     *     {@link GenericPartyType }
     *     
     */
    public void setAlternativeDisputeResolutionServiceProvider(GenericPartyType value) {
        this.alternativeDisputeResolutionServiceProvider = value;
    }

    /**
     * Gets the value of the eliminatedResponsibleParty property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the eliminatedResponsibleParty property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEliminatedResponsibleParty().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link GenericPartyType }
     * 
     * 
     */
    public List<GenericPartyType> getEliminatedResponsibleParty() {
        if (eliminatedResponsibleParty == null) {
            eliminatedResponsibleParty = new ArrayList<GenericPartyType>();
        }
        return this.eliminatedResponsibleParty;
    }

    /**
     * Gets the value of the additionalResponsibleParty property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the additionalResponsibleParty property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAdditionalResponsibleParty().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link GenericPartyType }
     * 
     * 
     */
    public List<GenericPartyType> getAdditionalResponsibleParty() {
        if (additionalResponsibleParty == null) {
            additionalResponsibleParty = new ArrayList<GenericPartyType>();
        }
        return this.additionalResponsibleParty;
    }

    /**
     * Gets the value of the salvor property.
     * 
     * @return
     *     possible object is
     *     {@link GenericPartyType }
     *     
     */
    public GenericPartyType getSalvor() {
        return salvor;
    }

    /**
     * Sets the value of the salvor property.
     * 
     * @param value
     *     allowed object is
     *     {@link GenericPartyType }
     *     
     */
    public void setSalvor(GenericPartyType value) {
        this.salvor = value;
    }

    /**
     * Gets the value of the salvageProvider property.
     * 
     * @return
     *     possible object is
     *     {@link GenericPartyType }
     *     
     */
    public GenericPartyType getSalvageProvider() {
        return salvageProvider;
    }

    /**
     * Sets the value of the salvageProvider property.
     * 
     * @param value
     *     allowed object is
     *     {@link GenericPartyType }
     *     
     */
    public void setSalvageProvider(GenericPartyType value) {
        this.salvageProvider = value;
    }

    /**
     * Gets the value of the vehicleResaleProvider property.
     * 
     * @return
     *     possible object is
     *     {@link GenericPartyType }
     *     
     */
    public GenericPartyType getVehicleResaleProvider() {
        return vehicleResaleProvider;
    }

    /**
     * Sets the value of the vehicleResaleProvider property.
     * 
     * @param value
     *     allowed object is
     *     {@link GenericPartyType }
     *     
     */
    public void setVehicleResaleProvider(GenericPartyType value) {
        this.vehicleResaleProvider = value;
    }

    /**
     * Gets the value of the billToParty property.
     * 
     * @return
     *     possible object is
     *     {@link GenericPartyType }
     *     
     */
    public GenericPartyType getBillToParty() {
        return billToParty;
    }

    /**
     * Sets the value of the billToParty property.
     * 
     * @param value
     *     allowed object is
     *     {@link GenericPartyType }
     *     
     */
    public void setBillToParty(GenericPartyType value) {
        this.billToParty = value;
    }

    /**
     * Gets the value of the remitToParty property.
     * 
     * @return
     *     possible object is
     *     {@link GenericPartyType }
     *     
     */
    public GenericPartyType getRemitToParty() {
        return remitToParty;
    }

    /**
     * Sets the value of the remitToParty property.
     * 
     * @param value
     *     allowed object is
     *     {@link GenericPartyType }
     *     
     */
    public void setRemitToParty(GenericPartyType value) {
        this.remitToParty = value;
    }

    /**
     * Gets the value of the serviceProvider property.
     * 
     * @return
     *     possible object is
     *     {@link GenericPartyType }
     *     
     */
    public GenericPartyType getServiceProvider() {
        return serviceProvider;
    }

    /**
     * Sets the value of the serviceProvider property.
     * 
     * @param value
     *     allowed object is
     *     {@link GenericPartyType }
     *     
     */
    public void setServiceProvider(GenericPartyType value) {
        this.serviceProvider = value;
    }

}
