//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.03 at 12:33:26 PM PST 
//


package com.mitchell.estimate.resource.dto.totals;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import com.mitchell.estimate.resource.dto.adjustment.TotalAdjustmentInfoType;
import com.mitchell.estimate.resource.dto.vehicle.UnitOfMeasureClosedEnumType;


/**
 * <p>Java class for TotalsInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TotalsInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TotalType" type="{http://www.cieca.com/BMS}TotalTypeOpenEnumType"/>
 *         &lt;element name="TotalSubType" type="{http://www.cieca.com/BMS}TotalSubTypeOpenEnumType" minOccurs="0"/>
 *         &lt;element name="TotalTypeDesc" type="{http://www.cieca.com/BMS}Char_30"/>
 *         &lt;element name="NonTaxableHours" type="{http://www.cieca.com/BMS}Decimal_Range_-9999.9-9999.9" minOccurs="0"/>
 *         &lt;element name="TaxableHours" type="{http://www.cieca.com/BMS}Decimal_Range_-9999.9-9999.9" minOccurs="0"/>
 *         &lt;element name="TotalHours" type="{http://www.cieca.com/BMS}Decimal_Range_-9999.9-9999.9" minOccurs="0"/>
 *         &lt;element name="UnitOfMeasure" type="{http://www.cieca.com/BMS}UnitOfMeasureClosedEnumType" minOccurs="0"/>
 *         &lt;element name="ItemQuantity" type="{http://www.cieca.com/BMS}Decimal_Range_0-9999999999.99" minOccurs="0"/>
 *         &lt;element name="UnitPrice" type="{http://www.cieca.com/BMS}Currency" minOccurs="0"/>
 *         &lt;element name="TotalTaxInfo" type="{http://www.cieca.com/BMS}TotalTaxInfoType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="TotalAdjustmentInfo" type="{http://www.cieca.com/BMS}TotalAdjustmentInfoType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="NonTaxableAmt" type="{http://www.cieca.com/BMS}Currency" minOccurs="0"/>
 *         &lt;element name="TaxableAmt" type="{http://www.cieca.com/BMS}Currency" minOccurs="0"/>
 *         &lt;element name="TaxTotalAmt" type="{http://www.cieca.com/BMS}Currency" minOccurs="0"/>
 *         &lt;element name="OtherChargesNonTaxableAmt" type="{http://www.cieca.com/BMS}Currency" minOccurs="0"/>
 *         &lt;element name="OtherChargesTaxableAmt" type="{http://www.cieca.com/BMS}Currency" minOccurs="0"/>
 *         &lt;element name="TotalAmt" type="{http://www.cieca.com/BMS}Currency" minOccurs="0"/>
 *         &lt;element name="TotalCost" type="{http://www.cieca.com/BMS}Currency" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TotalsInfoType", propOrder = {
    "totalType",
    "totalSubType",
    "totalTypeDesc",
    "nonTaxableHours",
    "taxableHours",
    "totalHours",
    "unitOfMeasure",
    "itemQuantity",
    "unitPrice",
    "totalTaxInfo",
    "totalAdjustmentInfo",
    "nonTaxableAmt",
    "taxableAmt",
    "taxTotalAmt",
    "otherChargesNonTaxableAmt",
    "otherChargesTaxableAmt",
    "totalAmt",
    "totalCost"
})
public class TotalsInfoType
    implements Serializable
{

    private final static long serialVersionUID = 20120730L;
    @XmlElement(name = "TotalType", required = true)
    protected String totalType;
    @XmlElement(name = "TotalSubType")
    protected String totalSubType;
    @XmlElement(name = "TotalTypeDesc", required = true)
    protected String totalTypeDesc;
    @XmlElement(name = "NonTaxableHours")
    protected BigDecimal nonTaxableHours;
    @XmlElement(name = "TaxableHours")
    protected BigDecimal taxableHours;
    @XmlElement(name = "TotalHours")
    protected BigDecimal totalHours;
    @XmlElement(name = "UnitOfMeasure")
    protected UnitOfMeasureClosedEnumType unitOfMeasure;
    @XmlElement(name = "ItemQuantity")
    protected BigDecimal itemQuantity;
    @XmlElement(name = "UnitPrice")
    protected BigDecimal unitPrice;
    @XmlElement(name = "TotalTaxInfo")
    protected List<TotalTaxInfoType> totalTaxInfo;
    @XmlElement(name = "TotalAdjustmentInfo")
    protected List<TotalAdjustmentInfoType> totalAdjustmentInfo;
    @XmlElement(name = "NonTaxableAmt")
    protected BigDecimal nonTaxableAmt;
    @XmlElement(name = "TaxableAmt")
    protected BigDecimal taxableAmt;
    @XmlElement(name = "TaxTotalAmt")
    protected BigDecimal taxTotalAmt;
    @XmlElement(name = "OtherChargesNonTaxableAmt")
    protected BigDecimal otherChargesNonTaxableAmt;
    @XmlElement(name = "OtherChargesTaxableAmt")
    protected BigDecimal otherChargesTaxableAmt;
    @XmlElement(name = "TotalAmt")
    protected BigDecimal totalAmt;
    @XmlElement(name = "TotalCost")
    protected BigDecimal totalCost;

    /**
     * Gets the value of the totalType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTotalType() {
        return totalType;
    }

    /**
     * Sets the value of the totalType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTotalType(String value) {
        this.totalType = value;
    }

    /**
     * Gets the value of the totalSubType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTotalSubType() {
        return totalSubType;
    }

    /**
     * Sets the value of the totalSubType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTotalSubType(String value) {
        this.totalSubType = value;
    }

    /**
     * Gets the value of the totalTypeDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTotalTypeDesc() {
        return totalTypeDesc;
    }

    /**
     * Sets the value of the totalTypeDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTotalTypeDesc(String value) {
        this.totalTypeDesc = value;
    }

    /**
     * Gets the value of the nonTaxableHours property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getNonTaxableHours() {
        return nonTaxableHours;
    }

    /**
     * Sets the value of the nonTaxableHours property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setNonTaxableHours(BigDecimal value) {
        this.nonTaxableHours = value;
    }

    /**
     * Gets the value of the taxableHours property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTaxableHours() {
        return taxableHours;
    }

    /**
     * Sets the value of the taxableHours property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTaxableHours(BigDecimal value) {
        this.taxableHours = value;
    }

    /**
     * Gets the value of the totalHours property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTotalHours() {
        return totalHours;
    }

    /**
     * Sets the value of the totalHours property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTotalHours(BigDecimal value) {
        this.totalHours = value;
    }

    /**
     * Gets the value of the unitOfMeasure property.
     * 
     * @return
     *     possible object is
     *     {@link UnitOfMeasureClosedEnumType }
     *     
     */
    public UnitOfMeasureClosedEnumType getUnitOfMeasure() {
        return unitOfMeasure;
    }

    /**
     * Sets the value of the unitOfMeasure property.
     * 
     * @param value
     *     allowed object is
     *     {@link UnitOfMeasureClosedEnumType }
     *     
     */
    public void setUnitOfMeasure(UnitOfMeasureClosedEnumType value) {
        this.unitOfMeasure = value;
    }

    /**
     * Gets the value of the itemQuantity property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getItemQuantity() {
        return itemQuantity;
    }

    /**
     * Sets the value of the itemQuantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setItemQuantity(BigDecimal value) {
        this.itemQuantity = value;
    }

    /**
     * Gets the value of the unitPrice property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getUnitPrice() {
        return unitPrice;
    }

    /**
     * Sets the value of the unitPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setUnitPrice(BigDecimal value) {
        this.unitPrice = value;
    }

    /**
     * Gets the value of the totalTaxInfo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the totalTaxInfo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTotalTaxInfo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TotalTaxInfoType }
     * 
     * 
     */
    public List<TotalTaxInfoType> getTotalTaxInfo() {
        if (totalTaxInfo == null) {
            totalTaxInfo = new ArrayList<TotalTaxInfoType>();
        }
        return this.totalTaxInfo;
    }

    /**
     * Gets the value of the totalAdjustmentInfo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the totalAdjustmentInfo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTotalAdjustmentInfo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TotalAdjustmentInfoType }
     * 
     * 
     */
    public List<TotalAdjustmentInfoType> getTotalAdjustmentInfo() {
        if (totalAdjustmentInfo == null) {
            totalAdjustmentInfo = new ArrayList<TotalAdjustmentInfoType>();
        }
        return this.totalAdjustmentInfo;
    }

    /**
     * Gets the value of the nonTaxableAmt property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getNonTaxableAmt() {
        return nonTaxableAmt;
    }

    /**
     * Sets the value of the nonTaxableAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setNonTaxableAmt(BigDecimal value) {
        this.nonTaxableAmt = value;
    }

    /**
     * Gets the value of the taxableAmt property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTaxableAmt() {
        return taxableAmt;
    }

    /**
     * Sets the value of the taxableAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTaxableAmt(BigDecimal value) {
        this.taxableAmt = value;
    }

    /**
     * Gets the value of the taxTotalAmt property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTaxTotalAmt() {
        return taxTotalAmt;
    }

    /**
     * Sets the value of the taxTotalAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTaxTotalAmt(BigDecimal value) {
        this.taxTotalAmt = value;
    }

    /**
     * Gets the value of the otherChargesNonTaxableAmt property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getOtherChargesNonTaxableAmt() {
        return otherChargesNonTaxableAmt;
    }

    /**
     * Sets the value of the otherChargesNonTaxableAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setOtherChargesNonTaxableAmt(BigDecimal value) {
        this.otherChargesNonTaxableAmt = value;
    }

    /**
     * Gets the value of the otherChargesTaxableAmt property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getOtherChargesTaxableAmt() {
        return otherChargesTaxableAmt;
    }

    /**
     * Sets the value of the otherChargesTaxableAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setOtherChargesTaxableAmt(BigDecimal value) {
        this.otherChargesTaxableAmt = value;
    }

    /**
     * Gets the value of the totalAmt property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTotalAmt() {
        return totalAmt;
    }

    /**
     * Sets the value of the totalAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTotalAmt(BigDecimal value) {
        this.totalAmt = value;
    }

    /**
     * Gets the value of the totalCost property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTotalCost() {
        return totalCost;
    }

    /**
     * Sets the value of the totalCost property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTotalCost(BigDecimal value) {
        this.totalCost = value;
    }

}
