//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.14 at 02:56:20 PM PST 
//


package com.mitchell.estimate.resource.dto.totals;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TotalSubTypeEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TotalSubTypeEnum">
 *   &lt;restriction base="{http://www.cieca.com/BMS}OpenEnum">
 *     &lt;enumeration value="1"/>
 *     &lt;enumeration value="18"/>
 *     &lt;enumeration value="AAH"/>
 *     &lt;enumeration value="BM"/>
 *     &lt;enumeration value="BTR"/>
 *     &lt;enumeration value="CA"/>
 *     &lt;enumeration value="CC"/>
 *     &lt;enumeration value="CE"/>
 *     &lt;enumeration value="D2"/>
 *     &lt;enumeration value="D8"/>
 *     &lt;enumeration value="ECT"/>
 *     &lt;enumeration value="F7"/>
 *     &lt;enumeration value="M8"/>
 *     &lt;enumeration value="ML"/>
 *     &lt;enumeration value="N"/>
 *     &lt;enumeration value="PN"/>
 *     &lt;enumeration value="RP"/>
 *     &lt;enumeration value="SM"/>
 *     &lt;enumeration value="T"/>
 *     &lt;enumeration value="T2"/>
 *     &lt;enumeration value="TT"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "TotalSubTypeEnum")
@XmlEnum
public enum TotalSubTypeEnum {

    @XmlEnumValue("1")
    VALUE_1("1"),
    @XmlEnumValue("18")
    VALUE_2("18"),
    @XmlEnumValue("AAH")
    VALUE_3("AAH"),
    @XmlEnumValue("BM")
    VALUE_4("BM"),
    @XmlEnumValue("BTR")
    VALUE_5("BTR"),
    @XmlEnumValue("CA")
    VALUE_6("CA"),
    @XmlEnumValue("CC")
    VALUE_7("CC"),
    @XmlEnumValue("CE")
    VALUE_8("CE"),
    @XmlEnumValue("D2")
    VALUE_9("D2"),
    @XmlEnumValue("D8")
    VALUE_10("D8"),
    @XmlEnumValue("ECT")
    VALUE_11("ECT"),
    @XmlEnumValue("F7")
    VALUE_12("F7"),
    @XmlEnumValue("M8")
    VALUE_13("M8"),
    @XmlEnumValue("ML")
    VALUE_14("ML"),
    @XmlEnumValue("N")
    VALUE_15("N"),
    @XmlEnumValue("PN")
    VALUE_16("PN"),
    @XmlEnumValue("RP")
    VALUE_17("RP"),
    @XmlEnumValue("SM")
    VALUE_18("SM"),
    @XmlEnumValue("T")
    VALUE_19("T"),
    @XmlEnumValue("T2")
    VALUE_20("T2"),
    @XmlEnumValue("TT")
    VALUE_21("TT");
    private final String value;

    TotalSubTypeEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TotalSubTypeEnum fromValue(String v) {
        for (TotalSubTypeEnum c: TotalSubTypeEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
