//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.03 at 12:33:26 PM PST 
//


package com.mitchell.estimate.resource.dto.adjustment;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AdjustmentTypeClosedEnumType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="AdjustmentTypeClosedEnumType">
 *   &lt;restriction base="{http://www.cieca.com/BMS}ClosedEnum">
 *     &lt;enumeration value="Accessories Adjustment"/>
 *     &lt;enumeration value="Adjustment"/>
 *     &lt;enumeration value="Aftermarket Parts Adjustment"/>
 *     &lt;enumeration value="Betterment"/>
 *     &lt;enumeration value="Betterment Labor"/>
 *     &lt;enumeration value="Betterment Labor Paint"/>
 *     &lt;enumeration value="Betterment Paint and Materials"/>
 *     &lt;enumeration value="Betterment Parts"/>
 *     &lt;enumeration value="Betterment Parts Labor"/>
 *     &lt;enumeration value="Betterment Parts Labor Paint"/>
 *     &lt;enumeration value="Betterment Parts Paint"/>
 *     &lt;enumeration value="Betterment Total Paint"/>
 *     &lt;enumeration value="Charity"/>
 *     &lt;enumeration value="Condition Adjustment"/>
 *     &lt;enumeration value="Damaged In Transit"/>
 *     &lt;enumeration value="Deductible"/>
 *     &lt;enumeration value="Discount"/>
 *     &lt;enumeration value="ETA Delay"/>
 *     &lt;enumeration value="Fees"/>
 *     &lt;enumeration value="Incomplete Part"/>
 *     &lt;enumeration value="Labor"/>
 *     &lt;enumeration value="License"/>
 *     &lt;enumeration value="Markup"/>
 *     &lt;enumeration value="More Damage Than Described"/>
 *     &lt;enumeration value="Not Matching"/>
 *     &lt;enumeration value="Perfect Part Price Adjust"/>
 *     &lt;enumeration value="Price/Competition"/>
 *     &lt;enumeration value="Prior Damage Adjustment"/>
 *     &lt;enumeration value="Quote"/>
 *     &lt;enumeration value="Refurbishment Adjustment"/>
 *     &lt;enumeration value="Regulatory Compliance"/>
 *     &lt;enumeration value="Restocking Charge"/>
 *     &lt;enumeration value="Settlement Adjustment"/>
 *     &lt;enumeration value="Specialty"/>
 *     &lt;enumeration value="Taxes"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "AdjustmentTypeClosedEnumType")
@XmlEnum
public enum AdjustmentTypeClosedEnumType {

    @XmlEnumValue("Accessories Adjustment")
    ACCESSORIES_ADJUSTMENT("Accessories Adjustment"),
    @XmlEnumValue("Adjustment")
    ADJUSTMENT("Adjustment"),
    @XmlEnumValue("Aftermarket Parts Adjustment")
    AFTERMARKET_PARTS_ADJUSTMENT("Aftermarket Parts Adjustment"),
    @XmlEnumValue("Betterment")
    BETTERMENT("Betterment"),
    @XmlEnumValue("Betterment Labor")
    BETTERMENT_LABOR("Betterment Labor"),
    @XmlEnumValue("Betterment Labor Paint")
    BETTERMENT_LABOR_PAINT("Betterment Labor Paint"),
    @XmlEnumValue("Betterment Paint and Materials")
    BETTERMENT_PAINT_AND_MATERIALS("Betterment Paint and Materials"),
    @XmlEnumValue("Betterment Parts")
    BETTERMENT_PARTS("Betterment Parts"),
    @XmlEnumValue("Betterment Parts Labor")
    BETTERMENT_PARTS_LABOR("Betterment Parts Labor"),
    @XmlEnumValue("Betterment Parts Labor Paint")
    BETTERMENT_PARTS_LABOR_PAINT("Betterment Parts Labor Paint"),
    @XmlEnumValue("Betterment Parts Paint")
    BETTERMENT_PARTS_PAINT("Betterment Parts Paint"),
    @XmlEnumValue("Betterment Total Paint")
    BETTERMENT_TOTAL_PAINT("Betterment Total Paint"),
    @XmlEnumValue("Charity")
    CHARITY("Charity"),
    @XmlEnumValue("Condition Adjustment")
    CONDITION_ADJUSTMENT("Condition Adjustment"),
    @XmlEnumValue("Damaged In Transit")
    DAMAGED_IN_TRANSIT("Damaged In Transit"),
    @XmlEnumValue("Deductible")
    DEDUCTIBLE("Deductible"),
    @XmlEnumValue("Discount")
    DISCOUNT("Discount"),
    @XmlEnumValue("ETA Delay")
    ETA_DELAY("ETA Delay"),
    @XmlEnumValue("Fees")
    FEES("Fees"),
    @XmlEnumValue("Incomplete Part")
    INCOMPLETE_PART("Incomplete Part"),
    @XmlEnumValue("Labor")
    LABOR("Labor"),
    @XmlEnumValue("License")
    LICENSE("License"),
    @XmlEnumValue("Markup")
    MARKUP("Markup"),
    @XmlEnumValue("More Damage Than Described")
    MORE_DAMAGE_THAN_DESCRIBED("More Damage Than Described"),
    @XmlEnumValue("Not Matching")
    NOT_MATCHING("Not Matching"),
    @XmlEnumValue("Perfect Part Price Adjust")
    PERFECT_PART_PRICE_ADJUST("Perfect Part Price Adjust"),
    @XmlEnumValue("Price/Competition")
    PRICE_COMPETITION("Price/Competition"),
    @XmlEnumValue("Prior Damage Adjustment")
    PRIOR_DAMAGE_ADJUSTMENT("Prior Damage Adjustment"),
    @XmlEnumValue("Quote")
    QUOTE("Quote"),
    @XmlEnumValue("Refurbishment Adjustment")
    REFURBISHMENT_ADJUSTMENT("Refurbishment Adjustment"),
    @XmlEnumValue("Regulatory Compliance")
    REGULATORY_COMPLIANCE("Regulatory Compliance"),
    @XmlEnumValue("Restocking Charge")
    RESTOCKING_CHARGE("Restocking Charge"),
    @XmlEnumValue("Settlement Adjustment")
    SETTLEMENT_ADJUSTMENT("Settlement Adjustment"),
    @XmlEnumValue("Specialty")
    SPECIALTY("Specialty"),
    @XmlEnumValue("Taxes")
    TAXES("Taxes");
    private final String value;

    AdjustmentTypeClosedEnumType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static AdjustmentTypeClosedEnumType fromValue(String v) {
        for (AdjustmentTypeClosedEnumType c: AdjustmentTypeClosedEnumType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
